storage:
  image:
    repository: ghcr.io/k8sstormcenter/storage
    tag: v0.3.177
nodeAgent:
  image:
    repository: ghcr.io/k8sstormcenter/node-agent
    tag: v0.3.179
    pullPolicy: Always
  bundleSigning:
    enabled: true
    trustPolicy: |
      {
        "classes": {
          "base": {
            "signers": ["key:1b962159c04a8b6dd5825b971d8417a144a1358d9e2f8c14368d14e1ebc67fbd"],
            "allowedSpecPaths": ["architectures", "capabilities", "execs", "opens", "syscalls", "seccompProfile", "endpoints", "imageID", "imageTag", "rulePolicies", "identifiedCallStacks", "labelSelector"]
          },
          "admission": {
            "signers": ["key:2c6bd5e1e52cd5721c986bde87e84c382984d8d3263ddde7fc89d2e9c90c3fb3"],
            "allowedSpecPaths": ["ingress", "egress"]
          },
          "overlay": {
            "signers": ["key:2c6bd5e1e52cd5721c986bde87e84c382984d8d3263ddde7fc89d2e9c90c3fb3"],
            "allowedSpecPaths": ["execs", "opens"]
          }
        }
      }
    signingKey: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIOZGo0BefIYHsIuBcqW1QT9mIKbNvwnbRfUo54YhZMwPoAoGCCqGSM49
      AwEHoUQDQgAE2ZMjWaL3fElcSuQcAtkn+aHs4RdcJF4rpoHZEBRjDieYM4eZNfWz
      8AqctspZD7WLYtjUsIsJgMBphB/wtcn1hw==
      -----END EC PRIVATE KEY-----
  config:
    alertManagerExporterUrls:
      - alertmanager.honey.svc.cluster.local:9093
    maxLearningPeriod: 2m
    learningPeriod: 2m
    updatePeriod: 10000m
    ruleCooldown:
      ruleCooldownDuration: 0h
      ruleCooldownAfterCount: 1000000000
      ruleCooldownOnProfileFailure: false
      ruleCooldownMaxSize: 20000
capabilities:
  runtimeDetection: enable
  configurationScan: disable
  nodeScan: disable
  nodeSbomGeneration: disable
  vulnerabilityScan: disable
  relevancy: disable
  admissionController: disable
  networkEventsStreaming: enable
alertCRD:
  installDefault: true
  scopeClustered: true
clusterName: bobexample
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,local-path-storage,gmp-system,gmp-public,storm,lightening,cert-manager,kube-flannel,ingress-nginx,olm,px-operator,honey,pl,clickhouse,chain-loadgen"
