storage:
  image:
    repository: ghcr.io/k8sstormcenter/storage
    tag: v0.3.177
nodeAgent:
  image:
    repository: ghcr.io/k8sstormcenter/node-agent
    tag: v0.3.184
    pullPolicy: Always
  bundleSigning:
    enabled: true
    trustPolicy: |
      {
        "policy": {
          "classes": {
            "admission": {
              "signers": [
                "key:2c6bd5e1e52cd5721c986bde87e84c382984d8d3263ddde7fc89d2e9c90c3fb3"
              ],
              "allowedSpecPaths": [
                "ingress",
                "egress"
              ]
            },
            "base": {
              "signers": [
                "key:1b962159c04a8b6dd5825b971d8417a144a1358d9e2f8c14368d14e1ebc67fbd"
              ],
              "allowedSpecPaths": [
                "architectures",
                "capabilities",
                "execs",
                "opens",
                "syscalls",
                "seccompProfile",
                "endpoints",
                "imageID",
                "imageTag",
                "rulePolicies",
                "identifiedCallStacks",
                "labelSelector"
              ]
            },
            "overlay": {
              "signers": [
                "key:2c6bd5e1e52cd5721c986bde87e84c382984d8d3263ddde7fc89d2e9c90c3fb3"
              ],
              "allowedSpecPaths": [
                "execs",
                "opens"
              ]
            }
          }
        },
        "annotations": {
          "signature.kubescape.io/certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXakNDQVFHZ0F3SUJBZ0lRQlRpY0tQVlREL042cExMVVl1TGs5REFLQmdncWhrak9QUVFEQWpBVU1SSXcKRUFZRFZRUURFd2xzYjJOaGJDMXJaWGt3SGhjTk1qWXdPREV4TVRNeU16TXpXaGNOTWpjd09ERXhNVE15TXpNegpXakFVTVJJd0VBWURWUVFERXdsc2IyTmhiQzFyWlhrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVEFnaVE5TVBtc1k4Lzl0aWFORWZGNThDZ0lqV2JBaUpBeEVEdnpGMUxtdE5QZk9YVHJLQ2xqMFBnRFhOR3QKQ09yWUtRWGx5TEE3YVJJa1o3ZUhyaU1Ub3pVd016QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd013REFZRFZSMFRBUUgvQkFJd0FEQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQmhTN1NXClQzVENKZGFndlVzeTBDRUxLK1dtZGNBNWtmdXlPQllycUo2UGNBSWdad0g0akpLaEh4d3E0cDk4T1k1Ukg2YmIKWkZBWjlkc0VZTkwwbTZrb1V0WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
          "signature.kubescape.io/identity": "local-key",
          "signature.kubescape.io/issuer": "local",
          "signature.kubescape.io/signature": "MEYCIQDsFdmvZmhPmg4JwbtKaIsfq8OoGJ2I2a6zECt5WeiaLQIhALybplCCXUjLQ14n/u86nnqp5I6I6miQkXmCl9ZGjcaZ",
          "signature.kubescape.io/timestamp": "1786454613"
        }
      }
  config:
    alertManagerExporterUrls:
      - alertmanager.honey.svc.cluster.local:9093
    maxLearningPeriod: 2m
    learningPeriod: 2m
    updatePeriod: 10000m
    ruleCooldown:
      ruleCooldownDuration: 0h
      ruleCooldownAfterCount: 1000000000
      ruleCooldownOnProfileFailure: false
      ruleCooldownMaxSize: 20000
capabilities:
  runtimeDetection: enable
  configurationScan: disable
  nodeScan: disable
  nodeSbomGeneration: disable
  vulnerabilityScan: disable
  relevancy: disable
  admissionController: disable
  nodeProfileService: disable
  networkEventsStreaming: disable
alertCRD:
  installDefault: true
  scopeClustered: true
clusterName: bobexample
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,local-path-storage,gmp-system,gmp-public,storm,lightening,cert-manager,kube-flannel,ingress-nginx,olm,px-operator,honey,pl,clickhouse,chain-loadgen"
