apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-chain/kind-ReplicaSet/name-chain-frontend-5b74946fd5
    kubescape.io/resource-size: "50"
    kubescape.io/status: completed
    kubescape.io/sync-checksum: dd7ee17135f2f8899ec8f0fd05f35897e6c49ddf604675f800a7a28152e279f5
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-chain/deployment-chain-frontend
  creationTimestamp: "2026-05-16T17:53:39Z"
  labels:
    kubescape.io/instance-template-hash: 5b74946fd5
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-frontend
    kubescape.io/workload-namespace: chain
    kubescape.io/workload-resource-version: "23345"
  name: replicaset-chain-frontend-5b74946fd5
  namespace: chain
  resourceVersion: "1"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    - CAP_NET_ADMIN
    endpoints:
    - direction: inbound
      endpoint: :8080/healthz
      headers:
        Connection:
        - close
        Host:
        - 10.42.0.199:8080
      internal: true
      methods:
      - GET
    - direction: inbound
      endpoint: :8080/api/products
      headers:
        Host:
        - chain-frontend.chain.svc:8080
      internal: true
      methods:
      - GET
    - direction: outbound
      endpoint: :8080/api/products
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - chain-backend.chain.svc:8080
      internal: true
      methods:
      - GET
    - direction: inbound
      endpoint: :8080/api/cache/eval
      headers:
        Host:
        - chain-frontend.chain.svc:8080
      internal: true
      methods:
      - POST
    execs:
    - args:
      - /chain-frontend
      path: /chain-frontend
    identifiedCallStacks: null
    imageID: ttl.sh/chain-frontend-3cef61dd-eda3-4ab8-9073-64ebd142cbba@sha256:533bebc82820a994d1c4ff767adef32c5d3bc30dd0128dd3e400175f9870b42c
    imageTag: ttl.sh/chain-frontend-5bffddd0-b145-4128-b94c-6df4dc4914bf:24h
    name: chain-frontend
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      path: /etc/localtime
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - bind
    - capset
    - clone
    - close
    - close_range
    - epoll_ctl
    - epoll_pwait
    - faccessat2
    - fchown
    - fstatfs
    - futex
    - getcwd
    - getpeername
    - getsockname
    - gettid
    - madvise
    - newfstatat
    - pread64
    - prlimit64
    - read
    - rt_sigreturn
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - sigaltstack
    - socket
    - tkill
    - write
status: {}
