apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-chain/kind-ReplicaSet/name-chain-backend-54b8946f8f
    kubescape.io/resource-size: "27"
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 8ae96cbdad9c469fa2a31967db854e88e5130bee27ff62de4958a116141425bd
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-chain/deployment-chain-backend
  creationTimestamp: "2026-05-16T17:53:39Z"
  labels:
    kubescape.io/instance-template-hash: 54b8946f8f
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-backend
    kubescape.io/workload-namespace: chain
    kubescape.io/workload-resource-version: "23341"
  name: replicaset-chain-backend-54b8946f8f
  namespace: chain
  resourceVersion: "1"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    - CAP_NET_ADMIN
    endpoints:
    - direction: inbound
      endpoint: :8080/healthz
      headers:
        Connection:
        - close
        Host:
        - 10.42.0.198:8080
      internal: true
      methods:
      - GET
    - direction: inbound
      endpoint: :8080/api/products
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - chain-backend.chain.svc:8080
      internal: true
      methods:
      - GET
    execs:
    - args:
      - /chain-backend
      path: /chain-backend
    identifiedCallStacks: null
    imageID: ttl.sh/chain-backend-3cef61dd-eda3-4ab8-9073-64ebd142cbba@sha256:6f0c3a5c94f4ae34e945c754ca4fcf3929898ea79d03be5fbf29af79bfc86204
    imageTag: ttl.sh/chain-backend-5bffddd0-b145-4128-b94c-6df4dc4914bf:24h
    name: chain-backend
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      path: /etc/localtime
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - epoll_ctl
    - futex
    - getpeername
    - getsockname
    - pread64
    - rt_sigprocmask
    - sched_getaffinity
    - write
status: {}
