apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/managed-by: User
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-frontend
    kubescape.io/workload-namespace: chain
  name: chain-frontend
  namespace: chain
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    - CAP_NET_ADMIN
    endpoints:
    - direction: inbound
      endpoint: :8080/healthz
      headers:
        Connection:
        - close
        Host:
        - 10.42.0.199:8080
      internal: true
      methods:
      - GET
    - direction: inbound
      endpoint: :8080/api/products
      headers:
        Host:
        - chain-frontend.chain.svc:8080
      internal: true
      methods:
      - GET
    - direction: outbound
      endpoint: :8080/api/products
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - chain-backend.chain.svc:8080
      internal: true
      methods:
      - GET
    - direction: inbound
      endpoint: :8080/api/cache/eval
      headers:
        Host:
        - chain-frontend.chain.svc:8080
      internal: true
      methods:
      - POST
    execs:
    - args:
      - /chain-frontend
      path: /chain-frontend
    identifiedCallStacks: null
    imageID: ghcr.io/k8sstormcenter/chain-frontend@sha256:0000000000000000000000000000000000000000000000000000000000000000
    imageTag: ghcr.io/k8sstormcenter/chain-frontend:latest
    name: chain-frontend
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      path: /etc/localtime
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ''
    syscalls:
    - bind
    - capset
    - clone
    - close
    - close_range
    - epoll_ctl
    - epoll_pwait
    - faccessat2
    - fchown
    - fstatfs
    - futex
    - getcwd
    - getpeername
    - getsockname
    - gettid
    - madvise
    - newfstatat
    - pread64
    - prlimit64
    - read
    - rt_sigreturn
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - sigaltstack
    - socket
    - tkill
    - write
status: {}
