apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: NetworkNeighborhood
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/managed-by: User
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-postgres
    kubescape.io/workload-namespace: chain
  name: chain-postgres
  namespace: chain
spec:
  containers:
  - egress: null
    ingress:
    - dns: ''
      dnsNames: null
      identifier: 9eee1023834c90907b714890a0afaf4f00f2f1758e46c60955cc65af97aa4753
      ipAddress: ''
      namespaceSelector: null
      podSelector:
        matchLabels:
          app: chain-backend
      ports:
      - name: TCP-5432
        port: 5432
        protocol: TCP
      type: internal
    name: pg-vuln
  ephemeralContainers: null
  initContainers: null
  matchLabels:
    app: chain-postgres
