apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: NetworkNeighborhood
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/managed-by: User
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-redis
    kubescape.io/workload-namespace: chain
  name: chain-redis
  namespace: chain
spec:
  containers:
  - egress: null
    ingress:
    - dns: ''
      dnsNames: null
      identifier: 848dd30b2832a5a08303b089c448b5a8e51d9ffeca76f0ff7b93060d50e44a36
      ipAddress: ''
      namespaceSelector: null
      podSelector:
        matchLabels:
          app: chain-frontend
      ports:
      - name: TCP-6379
        port: 6379
        protocol: TCP
      type: internal
    name: redis
  ephemeralContainers: null
  initContainers: null
  matchLabels:
    app: chain-redis
