apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: NetworkNeighborhood
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-chain/kind-ReplicaSet/name-chain-postgres-7cb4d6476b
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 02fb5edff0f905e547120ae43c4ab7e36e29d1a0d32022fb4f3eab524348853c
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-chain/deployment-chain-postgres
  creationTimestamp: "2026-05-16T17:24:08Z"
  labels:
    kubescape.io/instance-template-hash: 7cb4d6476b
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-postgres
    kubescape.io/workload-namespace: chain
    kubescape.io/workload-resource-version: "19241"
  name: replicaset-chain-postgres-7cb4d6476b
  namespace: chain
  resourceVersion: "1"
spec:
  containers:
  - egress: null
    ingress:
    - dns: ""
      dnsNames: null
      identifier: 9eee1023834c90907b714890a0afaf4f00f2f1758e46c60955cc65af97aa4753
      ipAddress: ""
      namespaceSelector: null
      podSelector:
        matchLabels:
          app: chain-backend
      ports:
      - name: TCP-5432
        port: 5432
        protocol: TCP
      type: internal
    name: pg-vuln
  ephemeralContainers: null
  initContainers: null
  matchLabels:
    app: chain-postgres
