# Redis 7.2.10 — last version vulnerable to CVE-2025-49844
# (Use-After-Free in Lua parser lparser.c)
#
# Deploys into its own "redis" namespace with:
#   Namespace, ServiceAccount, Role, RoleBinding, Deployment, Service
#
# Apply:  kubectl apply -f redis-vulnerable.yaml
# Verify: kubectl -n redis get pods
# Test:   kubectl -n redis exec deploy/redis -- redis-cli PING
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: bob-cve-2025-49844
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis
  namespace: redis
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis
  namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    # Disable protected mode (no auth, no bind restriction)
    protected-mode no
    bind 0.0.0.0
    port 6379

    # Persistence off — ephemeral for testing
    save ""
    appendonly no

    # Memory limit
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Logging
    loglevel notice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: "7.2.10"
    cve: CVE-2025-49844
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/version: "7.2.10"
    spec:
      serviceAccountName: redis
      containers:
        - name: redis
          image: redis:7.2.10-bookworm
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/redis
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
