apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-redis/kind-ReplicaSet/name-redis-b477756
    kubescape.io/resource-size: "129"
    kubescape.io/status: ready
    kubescape.io/sync-checksum: 1aa085bd1bfc0db1d705a80a6136756caae78e29ce569ad44238dde0d28cf0fb
    kubescape.io/wlid: wlid://cluster-default/namespace-redis/deployment-redis
  creationTimestamp: "2026-03-01T14:22:32Z"
  labels:
    kubescape.io/instance-template-hash: b477756
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: redis
    kubescape.io/workload-namespace: redis
    kubescape.io/workload-resource-version: "1047"
  name: replicaset-redis-b477756
  namespace: redis
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CAP_SETGID
    - CAP_SETPCAP
    - CAP_SETUID
    - CAP_SYS_ADMIN
    endpoints: null
    execs:
    - args:
      - /usr/local/bin/redis-cli
      - PING
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - GET
      - bobtest
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - INFO
      - server
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - ping
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - SET
      - bobtest
      - hello
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - DBSIZE
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - EVAL
      - return 'hello'
      - "0"
      path: /usr/local/bin/redis-cli
    - args:
      - /usr/local/bin/redis-cli
      - DEL
      - bobtest
      path: /usr/local/bin/redis-cli
    identifiedCallStacks: null
    imageID: docker.io/library/redis@sha256:8cd70b529aec2af55a072917098c1ae6f1d9eb975ac1cf36928c7d5af7574f08
    imageTag: docker.io/library/redis:7.2.10-bookworm
    name: redis
    opens:
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: .
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /102/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /102/task/102/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /108/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /108/task/108/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /11/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /11/task/11/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /114/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /114/task/114/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /120/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /120/task/120/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /126/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /126/task/126/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /132/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /132/task/132/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /138/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /138/task/138/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /144/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /144/task/144/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /150/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /150/task/150/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /156/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /156/task/156/fd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /162/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /162/task/162/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /168/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /168/task/168/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /17/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /17/task/17/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /175/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /175/task/175/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /181/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /181/task/181/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /187/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /187/task/187/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /193/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /193/task/193/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /199/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /199/task/199/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /205/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /205/task/205/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /22/setgroups
    - flags:
      - O_DIRECTORY
      - O_CLOEXEC
      - O_RDONLY
      path: /22/task/22/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /28/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /28/task/28/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /35/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /35/task/35/fd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /41/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /41/task/41/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /48/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /48/task/48/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /54/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /54/task/54/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /60/setgroups
    - flags:
      - O_DIRECTORY
      - O_CLOEXEC
      - O_RDONLY
      path: /60/task/60/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /66/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /66/task/66/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /72/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /72/task/72/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /78/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /78/task/78/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /84/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /84/task/84/fd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /90/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /90/task/90/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /96/setgroups
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /96/task/96/fd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/ld.so.cache
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/kernel/cap_last_cap
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_RDONLY
      path: /proc/⋯/stat
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/vm/overcommit_memory
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/enabled
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libcrypto.so.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libssl.so.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: 01_14_20_04.2057619804/token
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - brk
    - close
    - connect
    - epoll_ctl
    - epoll_wait
    - exit_group
    - fcntl
    - getpid
    - getrandom
    - ioctl
    - madvise
    - mmap
    - mprotect
    - munmap
    - newfstatat
    - open
    - openat
    - poll
    - pread64
    - prlimit64
    - read
    - readlink
    - recvfrom
    - rseq
    - sched_getaffinity
    - sendto
    - set_robust_list
    - set_tid_address
    - setsockopt
    - socket
    - uname
    - write
status: {}
