apiVersion: bobctl.k8sstormcenter.io/v1alpha1
kind: AttackSuite
metadata:
  name: redis-cve-2025-49844
  description: >-
    Redis exploit chain: CVE-2025-49844 (UAF in Lua parser) + CVE-2022-0543
    (Lua sandbox escape via package.loadlib). Phase 1 heap-sprays the Lua
    allocator, Phase 2 triggers GC mid-parse for UAF, Phase 3 escapes the
    sandbox and performs fileless execution (memfd_create + execve) to
    exfiltrate the Kubernetes SA token. Triggers R1005 detection.
target:
  service: redis
  namespace: redis
  port: 6379
  protocol: redis

attacks:
  - name: lua-heap-spray
    type: fileless
    redis:
      eval: |
        local spray = string.rep('A', 1024)
        for i=1,100 do redis.call('SET','spray_'..i, spray) end
        return 'sprayed'
    successIndicators:
      - responseContains: "sprayed"

  - name: lua-uaf-trigger
    type: fileless
    redis:
      eval: |
        collectgarbage('collect')
        local x = string.rep('B', 64)
        collectgarbage('collect')
        return x
    successIndicators:
      - responseContains: "B"

  - name: cve-2025-49844-exploit
    type: fileless
    redis:
      exploit: cve-2025-49844

expectedDetections:
  - attackType: fileless
    ruleID: R1005
    ruleName: "Fileless execution detected"
    containerName: redis
