apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/managed-by: User
  name: argocd-repo-server
  namespace: argocd
spec:
  architectures:
    - amd64
  capabilities:
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    - CAP_NET_ADMIN
  egress:
    - {dns: "", dnsNames: [charts.helm.sh], identifier: e14947516f312d9c20b5aaedac27e8e861f3c87f28ac60c43b207d1eac70e1ff, ipAddress: "", namespaceSelector: null, podSelector: null, ports: [{name: TCP-443, port: 443, protocol: TCP}], type: external}
    - {dns: "", dnsNames: [github.com], identifier: 1e2c3b8253ef65bbb38bb96e642bd3c6d40827f27a1f6c41435805be35b74c77, ipAddress: "", namespaceSelector: null, podSelector: null, ports: [{name: TCP-443, port: 443, protocol: TCP}], type: external}
    - {dns: "", dnsNames: null, identifier: 760ff312ee1dc2fb28f74beb6f89fd37143fc11476e33af1541f9426b37945a2, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app.kubernetes.io/name: argocd-redis}}, ports: [{name: TCP-6379, port: 6379, protocol: TCP}], type: internal}
    - {dns: "", dnsNames: null, identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3, ipAddress: "", namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}, podSelector: {matchLabels: {k8s-app: kube-dns}}, ports: [{name: UDP-53, port: 53, protocol: UDP}], type: internal}
  endpoints:
    - {direction: inbound, endpoint: ':6443/metrics', headers: {Accept-Encoding: [gzip], Host: ['*:6443']}, internal: true, methods: [GET]}
    - {direction: inbound, endpoint: ':8084/healthz', headers: {Connection: [close], Host: ['*:8084']}, internal: true, methods: [GET]}
  execs:
    - {args: [/usr/local/bin/gpg-wrapper.sh, ⋯⋯], path: /usr/bin/dash}
    - {args: [/usr/bin/git, ⋯⋯], path: /usr/bin/git}
    - {args: [/usr/bin/gpg, ⋯⋯], path: /usr/bin/gpg}
    - {args: [/usr/bin/gpg-agent, ⋯⋯], path: /usr/bin/gpg-agent}
    - {args: [/usr/bin/tini, ⋯⋯], path: /usr/bin/tini}
    - {args: [/usr/lib/git-core/git, ⋯⋯], path: /usr/lib/git-core/git}
    - {args: [/usr/lib/git-core/git-remote-https, ⋯⋯], path: /usr/lib/git-core/git-remote-http}
    - {args: [/usr/local/bin/argocd-repo-server, ⋯⋯], path: /usr/local/bin/argocd}
    - {args: [/usr/local/bin/helm, ⋯⋯], path: /usr/local/bin/helm}
    - {args: [/usr/local/bin/kustomize, ⋯⋯], path: /usr/local/bin/kustomize}
  identifiedCallStacks: null
  imageID: ""
  imageTag: ""
  ingress:
    - {dns: "", dnsNames: null, identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14, ipAddress: "", ipAddresses: [10.42.0.0/16, 10.244.0.0/16], namespaceSelector: null, podSelector: null, ports: [{name: TCP-8084, port: 8084, protocol: TCP}], type: external}
    - {dns: "", dnsNames: null, identifier: d93b79fbec160a0515c1632b70a626152653f142c3a311111243c31b0b0d1ce7, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app.kubernetes.io/name: argocd-application-controller, apps.kubernetes.io/pod-index: "0", statefulset.kubernetes.io/pod-name: argocd-application-controller-0}}, ports: [{name: TCP-8081, port: 8081, protocol: TCP}], type: internal}
    - {dns: "", dnsNames: null, identifier: 31d7c34d1bf8a60b5bbb32a25efd7bdd86ed364ef9618683438efd4d6a4b7962, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app.kubernetes.io/name: argocd-applicationset-controller}}, ports: [{name: TCP-8081, port: 8081, protocol: TCP}], type: internal}
  matchLabels:
    app.kubernetes.io/name: argocd-repo-server
  opens:
    - {flags: [O_APPEND, O_CLOEXEC, O_CREAT, O_DIRECTORY, O_EXCL, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY], path: /app/config/*}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /etc/host.conf}
    - {flags: [O_APPEND, O_CLOEXEC, O_CREAT, O_DIRECTORY, O_EXCL, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY], path: /helm-working-dir/*}
    - {flags: [O_APPEND, O_CLOEXEC, O_CREAT, O_DIRECTORY, O_EXCL, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY], path: /tmp/*}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/lib/x86_64-linux-gnu/⋯}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/local/bin/argocd}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/local/bin/helm}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/local/bin/kustomize}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/share/ca-certificates/mozilla/⋯}
    - {flags: [O_CLOEXEC, O_RDONLY], path: /usr/share/zoneinfo/Etc/UTC}
  rulePolicies:
    R0002:
      processAllowed:
        - runc:[1:CHILD]
        - runc:[1:INIT]
        - runc:[2:INIT]
        - runc:[3:INIT]
    R0004:
      processAllowed:
        - runc:[1:CHILD]
        - runc:[1:INIT]
        - runc:[2:INIT]
        - runc:[3:INIT]
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls: null
status: {}
