# Learned from the enriched argo chain (gitserver + benign-apps + loadgen), 2026-06-17.
# Refresh of the hand-crafted v1; reflects real repo-server renders.
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: NetworkNeighborhood
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-argocd/kind-ReplicaSet/name-argocd-repo-server-775878bb66
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 345e356892f4a5d55fe403f605334682a4c76a3219a4c5beca37d1725d6dbb5d
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-argocd/deployment-argocd-repo-server
  labels:
    kubescape.io/managed-by: bobctl
spec:
  containers:
  - egress:
    - dns: ''
      dnsNames: null
      identifier: e361490411a4c21bc957f79c12521094620231494e713259dfa15c2b07741b99
      ipAddress: ''
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: gitops
      podSelector:
        matchLabels:
          app: gitserver
      ports:
      - name: TCP-9418
        port: 9418
        protocol: TCP
      type: internal
    - dns: ''
      dnsNames: null
      identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
      ipAddress: ''
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
      ports:
      - name: UDP-53
        port: 53
        protocol: UDP
      type: internal
    ingress:
    - dns: ''
      dnsNames: null
      identifier: d93b79fbec160a0515c1632b70a626152653f142c3a311111243c31b0b0d1ce7
      ipAddress: ''
      namespaceSelector: null
      podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-application-controller
          apps.kubernetes.io/pod-index: '0'
          statefulset.kubernetes.io/pod-name: argocd-application-controller-0
      ports:
      - name: TCP-8081
        port: 8081
        protocol: TCP
      type: internal
    - dns: ''
      dnsNames: null
      identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
      ipAddress: 10.42.0.1
      namespaceSelector: null
      podSelector: null
      ports:
      - name: TCP-8084
        port: 8084
        protocol: TCP
      type: external
    name: argocd-repo-server
  ephemeralContainers: null
  initContainers: null
  matchLabels:
    app.kubernetes.io/name: argocd-repo-server
