expose:
  type: nodePort
  tls:
    enabled: false
 #   auto:
 #     commonName: "127.0.0.1"
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002

externalURL: https://127.0.0.1:30002

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
#      storageClass: "standard"
      size: 5Gi
    database:
#      storageClass: "standard"
      size: 1Gi
    redis:
#      storageClass: "standard"
      size: 1Gi

harborAdminPassword: "Harbor12345"

database:
  type: internal
  internal:
    password: "root123"
redis:
  internal:
    password: "redis123"