externalURL: https://xxxx
expose:
  type: nodeport
  tls:
    enabled: false
harborAdminPassword: "Harbor12345"
database:
  type: internal
  internal:
    password: "root123"
redis:
  internal:
    password: "redis123"