expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002

externalURL: http://127.0.0.1:30002

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "local-path"
      size: 5Gi
    database:
      storageClass: "local-path"
      size: 1Gi
    redis:
      storageClass: "local-path"
      size: 1Gi

harborAdminPassword: "Harbor12345"

database:
  type: internal
  internal:
    password: "root123"
redis:
  internal:
    password: "redis123"