apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/managed-by: User
    signature.kubescape.io/certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXakNDQVFHZ0F3SUJBZ0lRTDV1eEt3RWk1a3dZMkJwbDF1UWpBakFLQmdncWhrak9QUVFEQWpBVU1SSXcKRUFZRFZRUURFd2xzYjJOaGJDMXJaWGt3SGhjTk1qWXdPVEkwTVRBd05EUXhXaGNOTWpjd09USTBNVEF3TkRReApXakFVTVJJd0VBWURWUVFERXdsc2IyTmhiQzFyWlhrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUVdkZUU3MmxlQWp3NllNakh4dmxRb0VYRWtFZXl5QU94b3I0c2l1VWtuSzkvcjJYTTlDOFZDLzJiR0x5eG4KUDRpZ1R6dStIL3VSaVBvazE2anl4aHI0b3pVd016QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd013REFZRFZSMFRBUUgvQkFJd0FEQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQkNna1p4CkhSQ3Z4dVZkYTcvcDlqbGczaFlhaC8zOFRLd2JmVUQrNXdtRzFRSWdJRS81ZjVYODFTOTF5aWFCWnQxQ2gyTnIKR2NtNVdMemZsa2VIU2JUdkdKWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    signature.kubescape.io/content: H4sIAAAAAAAA/7xZ3XLiOhJ+lS3VXu0xNj8TlrA3yxJqT2qzIUVyzpyprZRLltugiSyp1DIJk8oTzMPMO82TbMkmxDAQsGHODWXL/X1fq91St9EzoZr/Dga5kqRPUMdPPqrEPlIDTKVaIbdcSf8hiwAZ1eBzFcxbEVjaIh554DImfTJU0lIuwdwYlXABxCMpWBpTS0n/mQgagUDSl5kQHpE0BdInBmKO5MUjqIE5K2rYjFtgNjOApP8/QtO4+4Hce4RRTSMuuOXFg+HgJhz+Ov54Tbz8+mIwDMe/jyaTy4tRaWgyGlyEt6PBZPjrcvR6dBcOLv57+Qq8Hd39+/Li7eZmOLh5u/vt7dGn2yXu3iPwBMy58Uw0tTPSJ4HSNoi4lTTlQT6tIOKyuGowwYlHqJnmnh9g2pgRjwjFqJgptG5AE490O38/Jx7RXE7J/Yv3s7RrSyGYOZhD1VbW379++/712xEyB/BpmiGUPSsG1mwyNLlKRHFWNi2NbaPeBZsBFXYWuBCGgs9BAmKYv1P/KC4DNObHkJVji8xwbTFAS41trN+lFC2Y/fxMl9nXRre8x1Rl0kLcAMuCpQJTMtluvGl0Yv18ZI98yWar+pQ+PmzTL4afteHS/uWvrX+8bIfPgMbb4Mvxhmxtx1megsrsNujbowYSj7TO3A/xyOGLvKbI2abIAbvYvUeUBrm+l+Y1wyOJoIXqOJxcjK+vPq176awCqjXIWEmxiLmpgynd+VQlfsvnkhl3uc42uLkZXbtaMA6Hk9HgLr/6ODlIwkKqGxs6KZU8gTwsJZU36rvJb9fD90XciqyHhnng6vBmvD5OfrSzdrFudj2+/tfVePifnH07JjNUxird/zrcAnO58boGy3O5Go/+GA2XKruhWB0mYh+VzyibQQ2wy2eX/dWhEvGRWzarOVtNER/j6jgDqMS8piiiCGKO1iifbeLfwyRcY6riTEA1XL4ZoKgG0kbNeQwmjChW1FtBY0hoJmxNtJtuNWiGrqgdglgW/+9fv+1uJipSbO0h9nDsr8479qKLy8loeDeefMrvRn8Mr8oZt2uP2luNf7Ka4FEwFTxijdkjoxqDp1630f3QmLfdo9TtIN1qy6mCRue0Gk7ipGRmoa0jbJ2SUDnGzokYp4yFeEoXT/o23A53wsmijdkvv5zSwS8nC91r1+1KARZ34L7yfVQ/g/4zKnkC6vJXgts1d25z9eh2bWP72LZ/rjnGHz/Z9tBqo1iQcAG4QAtpxTYqR+MCg2Ll5uU+BEkjAfGB2g79AEaCCBjVoaBoQ0Z1TT8k2IApAwGqlD4xJWUFN+ZpoOZgmEpTbsMUUmUWNfyYF3+hhcinktrMVGwRcw73LtnUqKxOIPJMdanGZVJxCazwCDaXr5MQOT6lm9j37S21FcwtxYfgb7t9Wy//e6q+ySSrNk2XLTHMOQN8z4td0ASXL7cOeLlY0jSwhkrU1IC04SybgqZTCA5efQdwzdxvqNM4RP4F9lNmaPY0TJJlBgEfaxSpd8k7JyIXPKLWmrzs+S2/fdasWP1KRHV6rTJ81V35Lb95HE2dnqrEUbeLKlOkOido+mdHTGbG0SqzcEy9I+ZTp4krw3WSZ0jXb/vt2ixr2XqEN5oZaDd6jqbpt45JFfc5KLiEY8OLILjMno5LmHq9cZngrRv2m36nfljyMnrsWyo6ab9TN2EUomi89rf53wxVu9utTJ+5teA2faP04jDKe4/gAhkVb8d4CIypVL+e+PWfVwd5y79TBswWh4rk5cUjIGOtuLQrPE/pFC4v8pPAKUdrFo2WHyv2AMbnar2J/ifOaPus22/2et0Oa7NO8gGaZ60k6rY651Gnl9B2uwPnrNWJ4KzZ6XTaXXp2HgGNW712r9uMe+fnUXLeI0vZOzr9s3VNJuBGCc7yM8znF4/wGKTlCYd4SIW4tZQ9rIKTUstmV8tj02dCtc5PYI0EC+jczM9mJUhL+qTo/Im3xYxLtFSyt/PWbUabB7JcTg1g8bf8yknzatFggjtdj9iFdjguLRhJBfFILNG97/zimqawmo9WxhaES7G74U3j9TTAKKuYEsUoKYxJ3z11eadVfAsCmFXGheLHyGw65rLNqaCmDN6Brgfh9bzaX4+GC4cexHEREEKcR7AMj5vay8v/AwAA//93uiEnQh8AAA==
    signature.kubescape.io/identity: local-key
    signature.kubescape.io/issuer: local
    signature.kubescape.io/signature: MEYCIQDajJ/o5QecOur3Fq7fa7IoFNg3tahd+6eRX46ZFp6SLwIhAIDknwHADc5Yo9k+Ihc1FM90TR0edyi5QGHFi2KCapom
    signature.kubescape.io/timestamp: "1790244281"
  name: redis
  namespace: redis
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_CHOWN
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_NET_ADMIN
  - CAP_SETGID
  - CAP_SETPCAP
  - CAP_SETUID
  - CAP_SYS_ADMIN
  egress: null
  endpoints: null
  execs:
  - args:
    - /opt/bitnami/redis/bin/redis-cli
    - -h
    - localhost
    - -p
    - "6379"
    - ping
    path: /opt/bitnami/redis/bin/redis-cli
  - args:
    - /opt/bitnami/redis/bin/redis-cli
    - -p
    - "6379"
    - ping
    path: /opt/bitnami/redis/bin/redis-cli
  - args:
    - /opt/bitnami/redis/bin/redis-server
    - ⋯⋯
    path: /opt/bitnami/redis/bin/redis-server
  - args:
    - redis-server
    - ⋯⋯
    path: /opt/bitnami/redis/bin/redis-server
  - args:
    - /pause
    path: /pause
  - args:
    - /bin/bash
    - ⋯⋯
    path: /usr/bin/bash
  - args:
    - /health/ping_liveness_local.sh
    - ⋯⋯
    path: /usr/bin/bash
  - args:
    - /health/ping_readiness_local.sh
    - ⋯⋯
    path: /usr/bin/bash
  - args:
    - /opt/bitnami/scripts/start-scripts/start-master.sh
    - ⋯⋯
    path: /usr/bin/bash
  - args:
    - /usr/bin/cp
    - /opt/bitnami/redis/mounted-etc/master.conf
    - /opt/bitnami/redis/etc/master.conf
    path: /usr/bin/cp
  - args:
    - /usr/bin/cp
    - /opt/bitnami/redis/mounted-etc/redis.conf
    - /opt/bitnami/redis/etc/redis.conf
    path: /usr/bin/cp
  - args:
    - /usr/bin/awk
    - '{print $1;}'
    path: /usr/bin/gawk
  - args:
    - /usr/bin/head
    - -n1
    path: /usr/bin/head
  - args:
    - /usr/bin/timeout
    - -s
    - "15"
    - "1"
    - redis-cli
    - -p
    - "6379"
    - ping
    path: /usr/bin/timeout
  - args:
    - /usr/bin/timeout
    - -s
    - "15"
    - "5"
    - redis-cli
    - -h
    - localhost
    - -p
    - "6379"
    - ping
    path: /usr/bin/timeout
  identifiedCallStacks: null
  imageID: registry-1.docker.io/bitnami/redis@sha256:08863c2c3f4e051fb6139b38fa223e9c13be5033326a59bead182860d899bf98
  imageTag: registry-1.docker.io/bitnami/redis@sha256:08863c2c3f4e051fb6139b38fa223e9c13be5033326a59bead182860d899bf98
  ingress:
  - dns: ""
    dnsNames: null
    identifier: redis-client
    ipAddress: ""
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: redis
    podSelector:
      matchLabels:
        app: redis-client
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: internal
  matchLabels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  opens:
  - flags:
    - O_RDONLY
    path: /data
  - flags:
    - O_RDONLY
    path: /data/appendonlydir
  - flags:
    - O_APPEND
    - O_CREAT
    - O_WRONLY
    path: /data/appendonlydir/appendonly.aof.1.incr.aof
  - flags:
    - O_CREAT
    - O_TRUNC
    - O_WRONLY
    path: /data/appendonlydir/temp-appendonly.aof.manifest
  - flags:
    - O_CREAT
    - O_TRUNC
    - O_WRONLY
    path: /data/⋯
  - flags:
    - O_RDWR
    path: /dev/null
  - flags:
    - O_NONBLOCK
    - O_RDWR
    path: /dev/tty
  - flags:
    - O_RDONLY
    path: /dev/urandom
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/host.conf
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/hosts
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/ld.so.cache
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/localtime
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/nsswitch.conf
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/passwd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/resolv.conf
  - flags:
    - O_RDONLY
    path: /etc/ssl/distro.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/fipsmodule.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/openssl.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_base.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_default.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_fips.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/user.cnf
  - flags:
    - O_RDONLY
    path: /health/⋯/ping_liveness_local.sh
  - flags:
    - O_RDONLY
    path: /health/⋯/ping_readiness_local.sh
  - flags:
    - O_CREAT
    - O_DIRECTORY
    - O_EXCL
    - O_RDONLY
    - O_WRONLY
    path: /opt/bitnami/redis/etc/master.conf
  - flags:
    - O_CREAT
    - O_DIRECTORY
    - O_EXCL
    - O_RDONLY
    - O_WRONLY
    path: /opt/bitnami/redis/etc/redis.conf
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/glibc-hwcaps/x86-64-v2/libm.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/glibc-hwcaps/x86-64-v3/libm.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libc.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libcrypt.so.1
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libcrypto.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libgcc_s.so.1
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libm.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libssl.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libstdc++.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libz.so.1
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/redis/modules/redisearch.so
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/redis/modules/rejson.so
  - flags:
    - O_RDONLY
    path: /opt/bitnami/redis/mounted-etc/⋯/master.conf
  - flags:
    - O_RDONLY
    path: /opt/bitnami/redis/mounted-etc/⋯/redis.conf
  - flags:
    - O_RDONLY
    path: /opt/bitnami/scripts/start-scripts/⋯/start-master.sh
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/filesystems
  - flags:
    - O_RDONLY
    path: /proc/sys/crypto/fips_enabled
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/sys/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    path: /proc/sys/net/core/somaxconn
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/sys/vm/overcommit_memory
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/version_signature
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/cgroup
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/mountinfo
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/setgroups
  - flags:
    - O_RDONLY
    path: /proc/⋯/smaps
  - flags:
    - O_RDONLY
    path: /proc/⋯/stat
  - flags:
    - O_CLOEXEC
    - O_DIRECTORY
    - O_RDONLY
    - O_WRONLY
    path: /proc/⋯/task/*
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /runc
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /sys/devices/*
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /sys/fs/cgroup/*
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/enabled
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/glibc-hwcaps/x86-64-v2/libncursesw.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/glibc-hwcaps/x86-64-v3/libncursesw.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libattr.so.1.1.2501
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libc.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libcrypt.so.1.1.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libcrypto.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libgcc_s.so.1
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libgmp.so.10.5.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libhistory.so.8.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libm.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libmpfr.so.6.2.2
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libncursesw.so.6.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libpcre2-8.so.0.11.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libreadline.so.8.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libselinux.so.1
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libssl.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libstdc++.so.6.0.30
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libtinfo.so.6.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libz.so.1.3.2
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/ossl-modules/fips.so
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/ossl-modules/jitterentropy.so
  rulePolicies: {}
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls: null
status: {}
