apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/managed-by: User
  name: backend
  namespace: java-poc
spec:
  architectures:
    - amd64
  capabilities: []
  egress:
    - {dns: "", dnsNames: null, identifier: egress-postgres, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app: postgres}}, ports: [{name: TCP-5432, port: 5432, protocol: TCP}], type: internal}
    - {dns: "", dnsNames: null, identifier: egress-kube-dns, ipAddress: "", namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}, podSelector: {matchLabels: {k8s-app: kube-dns}}, ports: [{name: UDP-53, port: 53, protocol: UDP}, {name: TCP-53, port: 53, protocol: TCP}], type: internal}
  endpoints:
    - {direction: inbound, endpoint: ':8080/api/login', internal: true, methods: [POST]}
    - {direction: inbound, endpoint: ':8080/api/products', internal: true, methods: [GET]}
    - {direction: inbound, endpoint: ':8080/healthz', internal: true, methods: [GET]}
  execs:
    - {args: [/opt/java/openjdk/bin/java, -jar, /app/app.jar], path: /opt/java/openjdk/bin/java}
    - {args: [/usr/bin/curl], path: /usr/bin/curl}
    - {args: [/usr/bin/java, -jar, /app/app.jar], path: /usr/bin/java}
    - {args: [/usr/bin/psql], path: /usr/bin/psql}
  identifiedCallStacks: null
  imageID: ghcr.io/k8sstormcenter/log4j-backend-vulnerable@sha256:689e1c1b29083b43845302f59e7f1706b7a0bf1ed825395ae4421fda957afcfd
  imageTag: ghcr.io/k8sstormcenter/log4j-backend-vulnerable:latest
  ingress:
    - {dns: "", dnsNames: null, identifier: ingress-from-frontend, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app: frontend}}, ports: [{name: TCP-8080, port: 8080, protocol: TCP}], type: internal}
    - {dns: "", dnsNames: null, identifier: ingress-from-observer, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app: observer}}, ports: [{name: TCP-8080, port: 8080, protocol: TCP}], type: internal}
  matchLabels:
    app: backend
  opens:
    - {flags: [O_RDONLY], path: /app/BOOT-INF/lib}
    - {flags: [O_RDONLY], path: /app/app.jar}
    - {flags: [O_RDONLY], path: /etc/group}
    - {flags: [O_RDONLY], path: /etc/host.conf}
    - {flags: [O_RDONLY], path: /etc/hosts}
    - {flags: [O_RDONLY], path: /etc/localtime}
    - {flags: [O_RDONLY], path: /etc/nsswitch.conf}
    - {flags: [O_RDONLY], path: /etc/passwd}
    - {flags: [O_RDONLY], path: /etc/resolv.conf}
    - {flags: [O_RDONLY], path: /opt/java/openjdk/conf}
    - {flags: [O_RDONLY], path: /opt/java/openjdk/conf/jndi.properties}
    - {flags: [O_RDONLY], path: /opt/java/openjdk/lib}
    - {flags: [O_RDONLY], path: /proc/sys/net}
    - {flags: [O_RDONLY], path: /root/.pgpass}
    - {flags: [O_CREAT, O_RDWR], path: /tmp}
    - {flags: [O_RDONLY], path: /usr/lib/jvm}
    - {flags: [O_RDONLY], path: /usr/lib/x86_64-linux-gnu/perl-base/IPC/Open3.pm}
    - {flags: [O_RDONLY], path: /usr/lib/x86_64-linux-gnu/perl-base/Symbol.pm}
    - {flags: [O_RDONLY], path: /usr/lib/x86_64-linux-gnu/perl-base/constant.pm}
    - {flags: [O_RDONLY], path: /usr/share/coreutils/locales/en-US.ftl}
    - {flags: [O_RDONLY], path: /usr/share/coreutils/locales/env/en-US.ftl}
    - {flags: [O_RDONLY], path: /usr/share/coreutils/locales/head/en-US.ftl}
    - {flags: [O_RDONLY], path: /usr/share/perl5/PgCommon.pm}
  rulePolicies:
    R0002:
      processAllowed:
        - Attach Listener
        - C1 CompilerThre
        - px_jattach
        - reservoir CompilerThre
        - runc:[1:INIT]
        - runc:[2:INIT]
        - runc:[3:INIT]
    R0004:
      processAllowed:
        - runc:[1:INIT]
        - runc:[2:INIT]
        - runc:[3:INIT]
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls: null
status: {}
