apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/managed-by: User
  name: observer
  namespace: java-poc
spec:
  architectures:
    - amd64
  capabilities: []
  egress:
    - {dns: "", dnsNames: null, identifier: egress-frontend, ipAddress: "", namespaceSelector: null, podSelector: {matchLabels: {app: frontend}}, ports: [{name: TCP-8080, port: 8080, protocol: TCP}], type: internal}
    - {dns: "", dnsNames: null, identifier: egress-kube-dns, ipAddress: "", namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}, podSelector: {matchLabels: {k8s-app: kube-dns}}, ports: [{name: UDP-53, port: 53, protocol: UDP}, {name: TCP-53, port: 53, protocol: TCP}], type: internal}
  endpoints: null
  execs:
    - {args: [/bin/sh, -c], path: /bin/sh}
    - {args: [/bin/sleep, "30"], path: /bin/sleep}
    - {args: [/usr/bin/curl, -s, 'http://frontend:8080/api/products'], path: /usr/bin/curl}
  identifiedCallStacks: null
  imageID: docker.io/curlimages/curl@sha256:33a4ef0dd8e9620625b14b373017d09ad8edc123588fd5aa806d4f55537739c7
  imageTag: docker.io/curlimages/curl:8.5.0
  ingress: null
  matchLabels:
    app: observer
  opens:
    - {flags: [O_RDONLY], path: /etc/hosts}
    - {flags: [O_RDONLY], path: /etc/localtime}
    - {flags: [O_RDONLY], path: /etc/nsswitch.conf}
    - {flags: [O_RDONLY], path: /etc/passwd}
    - {flags: [O_RDONLY], path: /etc/resolv.conf}
    - {flags: [O_RDONLY], path: /etc/ssl/certs/ca-certificates.crt}
  rulePolicies: {}
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls: null
status: {}
