apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: redis-base
  namespace: redis
  labels:
    signature.kubescape.io/bundle: redis
    signature.kubescape.io/fragment-class: base
  annotations:
    kubescape.io/managed-by: User
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_CHOWN
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_NET_ADMIN
  - CAP_SETGID
  - CAP_SETPCAP
  - CAP_SETUID
  - CAP_SYS_ADMIN
  egress: null
  endpoints: null
  execs:
  - args:
    - ⋯⋯
    path: /usr/bin/bash
  - args:
    - /usr/bin/timeout
    - ⋯⋯
    - ping
    - ⋯⋯
    path: /usr/bin/timeout
  - args:
    - /opt/bitnami/redis/bin/redis-cli
    - ⋯⋯
    - ping
    path: /opt/bitnami/redis/bin/redis-cli
  - args:
    - /usr/bin/cp
    - /opt/bitnami/redis/mounted-etc/master.conf
    - /opt/bitnami/redis/etc/master.conf
    - /opt/bitnami/redis/mounted-etc/redis.conf
    - /opt/bitnami/redis/etc/redis.conf
    path: /usr/bin/cp
  - args:
    - /opt/bitnami/redis/bin/redis-server
    - --port
    - '6379'
    - --protected-mode
    - 'no'
    - --include
    - /opt/bitnami/redis/etc/redis.conf
    - --include
    - /opt/bitnami/redis/etc/master.conf
    path: /opt/bitnami/redis/bin/redis-server
  - args:
    - /usr/bin/head
    - -n1
    path: /usr/bin/head
  - args:
    - /usr/bin/awk
    - '{print $1;}'
    path: /usr/bin/gawk
  identifiedCallStacks: null
  opens:
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libz.so.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /sys/devices/system/cpu/online
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/cgroup
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libc.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libz.so.1.3.2
  - flags:
    - O_RDONLY
    path: /etc/ssl/user.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/hosts
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /proc/⋯/task/⋯/fd
  - flags:
    - O_RDONLY
    path: /opt/bitnami/redis/mounted-etc/⋯/redis.conf
  - flags:
    - O_RDONLY
    path: /etc/ssl/openssl.cnf
  - flags:
    - O_RDONLY
    path: /proc/sys/crypto/fips_enabled
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libhistory.so.8.3
  - flags:
    - O_RDONLY
    path: /proc/sys/net/core/somaxconn
  - flags:
    - O_RDONLY
    path: /data
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libreadline.so.8.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/glibc-hwcaps/⋯/libncursesw.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libstdc++.so.6
  - flags:
    - O_RDONLY
    path: /sys/devices/system/clocksource/clocksource0/current_clocksource
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libcrypt.so.1
  - flags:
    - O_RDWR
    path: /dev/null
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/libssl.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/mounts
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/glibc-hwcaps/⋯/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/redis/modules/redisearch.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/setgroups
  - flags:
    - O_RDWR
    - O_NONBLOCK
    path: /dev/tty
  - flags:
    - O_RDONLY
    path: /health/⋯/ping_readiness_local.sh
  - flags:
    - O_RDONLY
    path: /dev/urandom
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libgcc_s.so.1
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/enabled
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/localtime
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - flags:
    - O_WRONLY
    - O_CREAT
    - O_TRUNC
    path: /data/⋯
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/ossl-modules/fips.so
  - flags:
    - O_RDONLY
    path: /data/appendonlydir
  - flags:
    - O_RDONLY
    path: /proc/⋯/stat
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/ld.so.cache
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/passwd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/filesystems
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/mountinfo
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/sys/vm/overcommit_memory
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/version_signature
  - flags:
    - O_RDONLY
    path: /opt/bitnami/scripts/start-scripts/⋯/start-master.sh
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libpcre2-8.so.0.11.0
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_default.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libstdc++.so.6.0.30
  - flags:
    - O_WRONLY
    - O_CREAT
    - O_TRUNC
    - O_APPEND
    path: /data/appendonlydir/⋯
  - flags:
    - O_RDONLY
    path: /health/⋯/ping_liveness_local.sh
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libgmp.so.10.5.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libmpfr.so.6.2.2
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/glibc-hwcaps/⋯/libncursesw.so.6
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/nsswitch.conf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libgcc_s.so.1
  - flags:
    - O_CREAT
    - O_EXCL
    - O_RDONLY
    - O_DIRECTORY
    - O_WRONLY
    path: /opt/bitnami/redis/etc/redis.conf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libtinfo.so.6.6
  - flags:
    - O_CREAT
    - O_EXCL
    - O_RDONLY
    - O_DIRECTORY
    - O_WRONLY
    path: /opt/bitnami/redis/etc/master.conf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/redis/modules/rejson.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/glibc-hwcaps/⋯/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /sys/fs/cgroup/cpu.max
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/resolv.conf
  - flags:
    - O_RDONLY
    path: /etc/ssl/distro.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_base.cnf
  - flags:
    - O_RDONLY
    path: /etc/ssl/fipsmodule.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libncursesw.so.6.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libssl.so.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /opt/bitnami/redis/lib/libc.so.6
  - flags:
    - O_RDONLY
    path: /etc/ssl/provider_fips.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libselinux.so.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opt/bitnami/redis/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/ossl-modules/jitterentropy.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libcrypt.so.1.1.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /runc
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/libattr.so.1.1.2501
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/sys/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    path: /proc/⋯/smaps
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/host.conf
  - flags:
    - O_RDONLY
    path: /opt/bitnami/redis/mounted-etc/⋯/master.conf
  rulePolicies:
    R0002:
      processAllowed:
      - runc:[1:INIT]
      - runc:[1:CHILD]
      - runc:[2:INIT]
      - runc:[3:INIT]
    R0004:
      processAllowed:
      - runc:[1:INIT]
      - runc:[1:CHILD]
      - runc:[2:INIT]
      - runc:[3:INIT]
