apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-shop/kind-ReplicaSet/name-nats-7b558f978b
    kubescape.io/resource-size: "5"
    kubescape.io/status: completed
    kubescape.io/sync-checksum: c7c576de818c40fc456b6c979bac02ebeb0d6ca0741899fd9e9a8e16c6767a6e
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-shop/deployment-nats
  creationTimestamp: "2026-06-17T13:21:59Z"
  labels:
    kubescape.io/instance-template-hash: 7b558f978b
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: nats
    kubescape.io/workload-namespace: shop
    kubescape.io/workload-resource-version: "145081"
  name: replicaset-nats-7b558f978b
  namespace: shop
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities: null
    endpoints: null
    execs: null
    identifiedCallStacks: null
    imageID: docker.io/natsio/nats-box@sha256:ffce8bd103383f179f8c7f11cf645726acf5d17280706c530c3b342dbe16334c
    imageTag: docker.io/natsio/nats-box:latest
    name: stream-init
    opens: null
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls: null
  - capabilities: null
    endpoints: null
    execs: null
    identifiedCallStacks: null
    imageID: docker.io/library/nats@sha256:b83efabe3e7def1e0a4a31ec6e078999bb17c80363f881df35edc70fcb6bb927
    imageTag: docker.io/library/nats:2.10-alpine
    name: nats
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/stat
    - flags:
      - O_RDWR
      - O_CLOEXEC
      path: /tmp/nats/jetstream/$G/streams/shopstream/msgs/index.db
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_TRUNC
      - O_CLOEXEC
      path: /tmp/nats/jetstream/$G/streams/shopstream/obs/shop-durable/o.dat
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - pwrite64
    - sysinfo
status: {}
