apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: NetworkNeighborhood
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-shop/kind-ReplicaSet/name-admin-5b4f6d7b9b
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 36bd05f334740e2a252f4c72be0af49ba9052144af2ccd6d27f85e0f51118047
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-shop/deployment-admin
  creationTimestamp: "2026-06-17T13:21:59Z"
  labels:
    kubescape.io/instance-template-hash: 5b4f6d7b9b
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: admin
    kubescape.io/workload-namespace: shop
    kubescape.io/workload-resource-version: "145131"
  name: replicaset-admin-5b4f6d7b9b
  namespace: shop
  resourceVersion: "2"
spec:
  containers:
  - egress: null
    ingress:
    - dns: ""
      dnsNames: null
      identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
      ipAddress: 10.42.0.1
      namespaceSelector: null
      podSelector: null
      ports:
      - name: TCP-3501
        port: 3501
        protocol: TCP
      type: external
    name: daprd
  - egress: null
    ingress: null
    name: app
  ephemeralContainers: null
  initContainers: null
  matchLabels:
    app: admin
