apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: dragonfly
  namespace: dragonfly
  annotations:
    kubescape.io/managed-by: User
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_IPC_LOCK
  egress:
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: internal
  - dns: version.dragonflydb.io.
    dnsNames:
    - version.dragonflydb.io.
    identifier: 988b5ed0477012e30ff4b8eabdc2e7d6528f23149964f5ed88079f9dc1d3348f
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-443
      port: 443
      protocol: TCP
    type: external
    ipAddresses:
    - 173.194.193.0/24
  endpoints: null
  execs:
  - args:
    - /usr/local/bin/dragonfly
    - --bind
    - 0.0.0.0
    - --port
    - '6379'
    - --requirepass=
    - --dbfilename
    - dump
    path: /usr/local/bin/dragonfly
  identifiedCallStacks: null
  ingress: null
  matchLabels:
    app.kubernetes.io/name: redis
  opens:
  - flags:
    - O_RDONLY
    path: /apex/com.android.tzdata/etc/tz/tzdata
  - flags:
    - O_RDONLY
    - O_NONBLOCK
    - O_DIRECTORY
    - O_CLOEXEC
    path: /data
  - flags:
    - O_RDONLY
    path: /data/misc/zoneinfo/current/tzdata
  - flags:
    - O_RDONLY
    path: /etc/hosts
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/ld.so.cache
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/localtime
  - flags:
    - O_RDONLY
    path: /etc/netsvc.conf
  - flags:
    - O_RDONLY
    path: /etc/nsswitch.conf
  - flags:
    - O_RDONLY
    path: /etc/resolv.conf
  - flags:
    - O_RDONLY
    path: /etc/ssl/certs/ca-certificates.crt
  - flags:
    - O_RDONLY
    path: /etc/svc.conf
  - flags:
    - O_RDONLY
    path: /ocal.sh
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯
  - flags:
    - O_RDONLY
    path: /proc/⋯/cgroup
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/status
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/task/⋯/fd
  - flags:
    - O_RDWR
    path: /proc/⋯/task/⋯/comm
  - flags:
    - O_RDONLY
    path: /proc/⋯/vm/overcommit_memory
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /sys/devices/system/cpu/cpu0/tsc_freq_khz
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /sys/devices/system/cpu/online
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/cpu.max
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/cpu/cpu.cfs_quota_us
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/cpu/cpu.max
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/memory.high
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/memory.limit_in_bytes
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/memory.max
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/memory/memory.limit_in_bytes
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/memory/memory.max
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/user.slice/cpu.cfs_quota_us
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/user.slice/memory.limit_in_bytes
  - flags:
    - O_RDONLY
    path: /sys/fs/cgroup/user.slice/memory.max
  - flags:
    - O_RDONLY
    path: /system/usr/share/zoneinfo/tzdata
  - flags:
    - O_APPEND
    - O_CLOEXEC
    - O_WRONLY
    - O_CREAT
    path: /tmp/dragonfly.unknown-user.INFO.20260801-175646.1.log
  - flags:
    - O_CLOEXEC
    - O_WRONLY
    - O_CREAT
    - O_APPEND
    path: /tmp/dragonfly.unknown-user.WARNING.20260801-175646.1.log
  - flags:
    - O_RDWR
    - O_CREAT
    - O_EXCL
    path: /tmp/helio-log-probe-J2nTuQ
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libc.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libdl.so.2
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libpthread.so.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/librt.so.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
  - flags:
    - O_RDONLY
    path: /usr/local/ssl/ssl/openssl.cnf
  rulePolicies:
    R0001: {}
    R0002: {}
    R0004: {}
    R0005: {}
    R0006: {}
    R0007: {}
    R0008: {}
    R0009: {}
    R0010: {}
    R0011: {}
    R0040: {}
    R1000: {}
    R1001: {}
    R1002: {}
    R1004: {}
    R1005: {}
    R1006: {}
    R1007: {}
    R1008: {}
    R1009: {}
    R1010: {}
    R1012: {}
    R1015: {}
    R1016: {}
    R1030:
      processAllowed:
      - Proactor0
      - Proactor1
      - Proactor2
      - Proactor3
      - Proactor4
      - Proactor5
      - Proactor6
      - Proactor7
      - Proactor8
      - Proactor9
      - Proactor10
      - Proactor11
      - Proactor12
      - Proactor13
      - Proactor14
      - Proactor15
    R1031: {}
    R2000: {}
