apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: keydb
  namespace: keydb
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_NET_ADMIN
  - CAP_SETGID
  - CAP_SETPCAP
  - CAP_SETUID
  - CAP_SYS_ADMIN
  egress:
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: internal
  - dns: api.keydb.dev.
    dnsNames:
    - api.keydb.dev.
    identifier: d34a80c7c584d2469a69916cea79b7d6eb4856d690018531f5b3b7bec42b88a7
    ipAddress: 18.221.162.228
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-80
      port: 80
      protocol: TCP
    type: external
  - dns: ''
    dnsNames: null
    identifier: e656ed0238ada70c2ec985b2a57b11dbb945d58c1c4e799cbfceaeefe67ebc26
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: keydb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keydb
        app.kubernetes.io/version: 6.3.2
        apps.kubernetes.io/pod-index: '1'
        helm.sh/chart: keydb-0.48.0
        statefulset.kubernetes.io/pod-name: keydb-1
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: internal
  - dns: ''
    dnsNames: null
    identifier: acf3acacc39ccc3af4417be8024ad8537d2ca7987f2677ef3a655b4280359f7e
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: keydb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keydb
        app.kubernetes.io/version: 6.3.2
        apps.kubernetes.io/pod-index: '2'
        helm.sh/chart: keydb-0.48.0
        statefulset.kubernetes.io/pod-name: keydb-2
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: internal
  endpoints:
  - direction: outbound
    endpoint: :80/motd/motd_server.txt
    headers:
      Host:
      - api.keydb.dev
    internal: false
    methods:
    - GET
  execs:
  - args:
    - /utils/server.sh
    path: /bin/bash
  - args:
    - /health/ping_readiness_local.sh
    - '1'
    path: /bin/bash
  - args:
    - /bin/sh
    - -c
    - /health/ping_readiness_local.sh 1
    path: /bin/dash
  - args:
    - /usr/local/bin/keydb-cli
    - -h
    - localhost
    - -p
    - '6379'
    - GET
    - 90f717dd-0e68-43b8-9363-fddaad00d6c9
    path: /usr/local/bin/keydb-cli
  - args:
    - /health/ping_liveness_local.sh
    - '5'
    path: /bin/bash
  - args:
    - /usr/local/bin/keydb-server
    - /etc/keydb/redis.conf
    - --active-replica
    - 'yes'
    - --multi-master
    - 'yes'
    - --appendonly
    - 'no'
    - --bind
    - 0.0.0.0
    - --port
    - '6379'
    - --protected-mode
    - 'no'
    - --server-threads
    - '2'
    - --replicaof keydb-1.keydb-headless 6379
    - --replicaof keydb-2.keydb-headless 6379
    path: /usr/local/bin/keydb-server
  - args:
    - /usr/bin/timeout
    - -s
    - '15'
    - '1'
    - keydb-cli
    - -h
    - localhost
    - -p
    - '6379'
    - GET
    - 90f717dd-0e68-43b8-9363-fddaad00d6c9
    path: /usr/bin/timeout
  - args:
    - /bin/sh
    - -c
    - /health/ping_liveness_local.sh 5
    path: /bin/dash
  - args:
    - /usr/bin/timeout
    - -s
    - '15'
    - '5'
    - keydb-cli
    - -h
    - localhost
    - -p
    - '6379'
    - PING
    path: /usr/bin/timeout
  - args:
    - /usr/local/bin/keydb-cli
    - -h
    - localhost
    - -p
    - '6379'
    - PING
    path: /usr/local/bin/keydb-cli
  - args:
    - /bin/hostname
    path: /bin/hostname
  identifiedCallStacks: null
  imageID: docker.io/eqalpha/keydb@sha256:fd9351ce27a7255cb5dbc71196bd2b040632180c95bb73804dbef5d234db7865
  imageTag: docker.io/eqalpha/keydb:x86_64_v6.3.2
  ingress:
  - dns: ''
    dnsNames: null
    identifier: e656ed0238ada70c2ec985b2a57b11dbb945d58c1c4e799cbfceaeefe67ebc26
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: keydb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keydb
        app.kubernetes.io/version: 6.3.2
        apps.kubernetes.io/pod-index: '1'
        helm.sh/chart: keydb-0.48.0
        statefulset.kubernetes.io/pod-name: keydb-1
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: internal
  - dns: ''
    dnsNames: null
    identifier: acf3acacc39ccc3af4417be8024ad8537d2ca7987f2677ef3a655b4280359f7e
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: keydb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keydb
        app.kubernetes.io/version: 6.3.2
        apps.kubernetes.io/pod-index: '2'
        helm.sh/chart: keydb-0.48.0
        statefulset.kubernetes.io/pod-name: keydb-2
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: internal
  matchLabels:
    app.kubernetes.io/instance: keydb
    app.kubernetes.io/name: keydb
  opens:
  - flags:
    - O_CLOEXEC
    - O_CREAT
    - O_EXCL
    - O_NONBLOCK
    - O_RDONLY
    - O_RDWR
    - O_TRUNC
    - O_WRONLY
    path: /*
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /*/cgroup
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /*/cgroup/cpu.max
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /*/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    path: /*/keydb.conf
  - flags:
    - O_RDONLY
    path: /*/mm/transparent_hugepage/enabled
  - flags:
    - O_RDONLY
    path: /*/mm/transparent_hugepage/hpage_pmd_size
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /*/mountinfo
  - flags:
    - O_RDONLY
    path: /*/net/core/somaxconn
  - flags:
    - O_RDONLY
    path: /*/oom_score_adj
  - flags:
    - O_RDONLY
    path: /*/ping_liveness_local.sh
  - flags:
    - O_RDONLY
    path: /*/ping_readiness_local.sh
  - flags:
    - O_RDONLY
    path: /*/server.sh
  - flags:
    - O_RDONLY
    path: /*/smaps
  - flags:
    - O_RDONLY
    path: /*/ssl/openssl.cnf
  - flags:
    - O_RDONLY
    path: /*/stat
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /*/system/cpu/online
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/1/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/101/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/110/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/119/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/128/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/137/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/146/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/155/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/164/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/173/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/182/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/191/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/200/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/21/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/210/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/219/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/228/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/238/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/247/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/256/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/266/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/275/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/284/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/293/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/30/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/303/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/312/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/321/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/331/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/340/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/349/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/358/fd
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /*/task/367/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/376/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/38/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/385/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/47/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/55/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/64/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/73/fd
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/82/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_DIRECTORY
    path: /*/task/91/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /*/vm/overcommit_memory
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/gai.conf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc/host.conf
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /lib/x86_64-linux-gnu/libbz2.so.1.0.4
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libc-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libcom_err.so.2.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libcrypt-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libdl-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libgcc_s.so.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libkeyutils.so.1.5
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libm-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libnsl-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libnss_compat-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libnss_dns-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libnss_files-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libnss_nis-2.27.so
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /lib/x86_64-linux-gnu/libpthread-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libresolv-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/librt-2.27.so
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libtinfo.so.5.9
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libuuid.so.1.3.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /lib/x86_64-linux-gnu/libz.so.1.2.11
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libhogweed.so.4.5
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.8
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.8
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libnettle.so.6.5
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.15.2
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libpsl.so.5.2.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/librtmp.so.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libsnappy.so.1.1.7
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.5
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: "/\u22EF"
  rulePolicies: {}
  seccompProfile:
    spec:
      defaultAction: ''
