# Default values for redis-bob.
kubescape-operator:
  enabled: true
  nodeAgent:
    config:
      maxLearningPeriod: 5m
      learningPeriod: 2m
      updatePeriod: 1m
      ruleCooldown:
        ruleCooldownDuration: 0h
        ruleCooldownAfterCount: 1000000000
        ruleCooldownOnProfileFailure: false
        ruleCooldownMaxSize: 20000
  capabilities:
    runtimeDetection: "enable"
    networkEventsStreaming: "disable"
    configurations:
      persistence: false
  alertCRD:
    installDefault: true
    scopeClustered: true
  clusterName: bobexample
  ksNamespace: bob ## You MUST install the whole umbrella into the same ns, at the moment -> rewrite into helmfile is known issue
  excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public,honey,storm,lightening,cert-manager,openebs,kube-flannel,ingress-nginx,olm,pl,px-operator"



redis: 
  architecture: standalone
  auth:
    enabled: false
  resources:
    requests:
      cpu: 2
      memory: 512Mi
    limits:
      cpu: 3
      memory: 1024Mi
  master:
    pdb:
      minAvailable: 0


bob:
  clusterName: "bobexample"
  #if set to false, the bob supplied by the vendor is not installed
  create: false
  # this gets overwritten in the two step release process #this is hackish
  templateHash: "67965968bb" 
  # this adds/removes an annotation to the entire deployment for kubescape to ignore it
  ignore: false