# Default values for redis-bob.
kubescape-operator:
  enabled: true
  nodeAgent:
    config:
      maxLearningPeriod: 5m
      learningPeriod: 2m
      updatePeriod: 1m
      ruleCooldown:
        ruleCooldownDuration: 0h
        ruleCooldownAfterCount: 1000000000
        ruleCooldownOnProfileFailure: false
        ruleCooldownMaxSize: 20000
  capabilities:
    runtimeDetection: "enable"
    networkEventsStreaming: "disable"
    configurations:
      persistence: false
  alertCRD:
    installDefault: true
    scopeClustered: true
  clusterName: bobexample
  ksNamespace: bob ## You MUST install the whole umbrella into the same ns, at the moment -> rewrite into helmfile is known issue
  excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public,honey,storm,lightening,cert-manager,openebs,kube-flannel,ingress-nginx,olm,pl,px-operator"



redis: 
  architecture: standalone
  auth:
    enabled: false
  resources:
    requests:
      cpu: 2
      memory: 512Mi
    limits:
      cpu: 3
      memory: 1024Mi
  master:
    pdb:
      minAvailable: 0
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false


bob:
  clusterName: "bobexample"
  #if set to false, the bob supplied by the vendor is not installed
  create: true
  # this gets overwritten in the two step release process #this is hackish
  templateHash: "849b7c549c" #orig image 
  # this adds/removes an annotation to the entire deployment for kubescape to ignore it
  ignore: false
  imageID: docker.io/bitnami/redis@sha256:5261cae9e4076b75d114e6bb032a0699c50b004ea06a680a5304c4c08d286adb
  imageTag: docker.io/bitnami/redis:7.2.5-debian-12-r0
