redis:
  image: 
    repository: redis
    tag: 8.2-rc1-bookworm
    digest: sha256:a4cfcdd802889c31b3eaa9c3178f4fe95b63b960128022f2245ba8be9fad2ff8
  architecture: standalone
  auth:
    enabled: false
  resources:
    requests:
      cpu: 2
      memory: 512Mi
    limits:
      cpu: 3
      memory: 1024Mi
  master:
    pdb:
      minAvailable: 0
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
  
bob:
  clusterName: "bobexample"
  #if set to false, the bob supplied by the vendor is not installed
  create: false
  # this gets overwritten in the two step release process #this is hackish
  templateHash: "59ffc7bcc9" #bookworm image 
  # this adds/removes an annotation to the entire deployment for kubescape to ignore it
  ignore: false
  imageID: docker.io/library/redis@sha256:a4cfcdd802889c31b3eaa9c3178f4fe95b63b960128022f2245ba8be9fad2ff8
  imageTag: docker.io/library/redis:8.2-rc1-bookworm
