apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: CollapseConfiguration
metadata: {name: default}
spec:
  openDynamicThreshold: 100000
  endpointDynamicThreshold: 100000
  collapseConfigs:
  - {prefix: /, threshold: 1000}
  - {prefix: /etc, threshold: 100}
  - {prefix: /etc/apache2, threshold: 50}
  - {prefix: /opt, threshold: 50}
  - {prefix: /var/run, threshold: 50}
  - {prefix: /app, threshold: 50}
  - {prefix: /home/argocd/.kube/cache, threshold: 1}
  - {prefix: /tmp/_argocd-repo, threshold: 1}
  - {prefix: /helm-working-dir, threshold: 1}
  - {prefix: /data, threshold: 1}
  - {prefix: /tmp/kustomization-, threshold: 1}
  - {prefix: /tmp/helmrelease-, threshold: 1}
  - {prefix: /tmp/gitrepository-, threshold: 1}
  - {prefix: /tmp/ocirepository-, threshold: 1}
  - {prefix: /tmp/chart-index-, threshold: 1}
  - {prefix: /tmp/helmchart-, threshold: 1}
  - {prefix: /tmp/bucket-, threshold: 1}
  - {prefix: /tmp/fetch., threshold: 1}
  - {prefix: /tmp/artifact-, threshold: 1}
