apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-DaemonSet/name-gke-metadata-server-7d5bf8764d
    kubescape.io/resource-size: "47"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/daemonset-gke-metadata-server
  creationTimestamp: "2025-12-14T17:59:45Z"
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: DaemonSet
    kubescape.io/workload-name: gke-metadata-server
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765720665419791020"
  name: daemonset-gke-metadata-server-7d5bf8764d
  namespace: kube-system
  resourceVersion: "3"
spec:
  architectures:
  - amd64
  containers:
  - capabilities: null
    endpoints:
    - direction: inbound
      endpoint: :989/healthz
      headers:
        Connection:
        - close
        Host:
        - 127.0.0.1:989
      internal: false
      methods:
      - GET
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metadata-server@sha256:0540ea9dca33cdd4b4f3805b7fd7a2ed761492c038a047dd169da69b135a6272
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metadata-server@sha256:0540ea9dca33cdd4b4f3805b7fd7a2ed761492c038a047dd169da69b135a6272
    name: gke-metadata-server
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/netstat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/snmp
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - clone
    - close
    - connect
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit_group
    - fcntl
    - flock
    - fstat
    - futex
    - getpeername
    - getpid
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - ioctl
    - madvise
    - mmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - pread64
    - read
    - readlinkat
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - setsockopt
    - sigaltstack
    - socket
    - tgkill
    - uname
    - waitid
    - write
status: {}
