apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-DaemonSet/name-pdcsi-node-74c9ccd8b6
    kubescape.io/resource-size: "252"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/daemonset-pdcsi-node
  creationTimestamp: "2025-12-14T20:05:53Z"
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: DaemonSet
    kubescape.io/workload-name: pdcsi-node
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765742442178047021"
  name: daemonset-pdcsi-node-74c9ccd8b6
  namespace: kube-system
  resourceVersion: "8"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    - SYS_ADMIN
    endpoints:
    - direction: outbound
      endpoint: :80/computeMetadata/v1/project/project-id
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 169.254.169.254
      internal: false
      methods:
      - GET
    - direction: outbound
      endpoint: :80/computeMetadata/v1/instance/name
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 169.254.169.254
      internal: false
      methods:
      - GET
    - direction: outbound
      endpoint: :80/computeMetadata/v1/instance/machine-type
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 169.254.169.254
      internal: false
      methods:
      - GET
    - direction: outbound
      endpoint: :80/computeMetadata/v1/instance/zone
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 169.254.169.254
      internal: false
      methods:
      - GET
    execs:
    - args:
      - /bin/sed
      - -i
      - -e
      - "s/.*locking_dir = .*/\t locking_dir = \"\\/tmp\"/"
      - /etc/lvm/lvm.conf
      path: /bin/sed
    - args:
      - /gce-pd-csi-driver
      - --v=5
      - --endpoint=unix:/csi/csi.sock
      - --run-controller-service=false
      - --run-node-service=true
      - --enable-data-cache=true
      - --node-name=gke-k8s-caas-0009-beta-user-pool-5a7e10f2-5fbt
      path: /gce-pd-csi-driver
    - args:
      - /bin/umount
      - /tmp/kubelet-detect-safe-umount3310381331
      path: /bin/umount
    - args:
      - /initialize-driver.sh
      - --v=5
      - --endpoint=unix:/csi/csi.sock
      - --run-controller-service=false
      - --run-node-service=true
      - --enable-data-cache=true
      - --node-name=gke-k8s-caas-0009-beta-user-pool-5a7e10f2-5fbt
      path: /initialize-driver.sh
    - args:
      - /bin/cp
      - -r
      - /lvm-tmp/lvm
      - /etc/
      path: /bin/cp
    - args:
      - /bin/sed
      - -i
      - -e
      - "s/.*allow_mixed_block_sizes = 0.*/\tallow_mixed_block_sizes = 1/"
      - /etc/lvm/lvm.conf
      path: /bin/sed
    - args:
      - /bin/sed
      - -i
      - -e
      - "s/.*udev_sync = 1.*/\tudev_sync = 0/"
      - /etc/lvm/lvm.conf
      path: /bin/sed
    - args:
      - /bin/sed
      - -i
      - -e
      - "s/.*udev_rules = 1.*/\tudev_rules = 0/"
      - /etc/lvm/lvm.conf
      path: /bin/sed
    - args:
      - /gce-pd-csi-driver
      - --v=5
      - --endpoint=unix:/csi/csi.sock
      - --run-controller-service=false
      - --run-node-service=true
      - --enable-data-cache=true
      - --node-name=gke-k8s-caas-0009-be-default-node-poo-08c84be6-qrtj
      path: /gce-pd-csi-driver
    - args:
      - /bin/umount
      - /tmp/kubelet-detect-safe-umount3805061794
      path: /bin/umount
    - args:
      - /initialize-driver.sh
      - --v=5
      - --endpoint=unix:/csi/csi.sock
      - --run-controller-service=false
      - --run-node-service=true
      - --enable-data-cache=true
      - --node-name=gke-k8s-caas-0009-be-default-node-poo-08c84be6-qrtj
      path: /initialize-driver.sh
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gcp-compute-persistent-disk-csi-driver@sha256:6d77d3847e228b9298cd78a54c4600eaccd819cd648fd13268d7eecaa419bd52
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gcp-compute-persistent-disk-csi-driver@sha256:6d77d3847e228b9298cd78a54c4600eaccd819cd648fd13268d7eecaa419bd52
    name: gce-pd-driver
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /dev/null
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      path: /etc
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      - O_RDONLY
      path: /etc/lvm/lvm.conf
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/lvmlocal.conf
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/cache-mq.profile
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/cache-smq.profile
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/command_profile_template.profile
    - flags:
      - O_EXCL
      - O_WRONLY
      - O_CREAT
      path: /etc/lvm/profile/lvmdbusd.profile
    - flags:
      - O_CREAT
      - O_EXCL
      - O_WRONLY
      path: /etc/lvm/profile/metadata_profile_template.profile
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/thin-generic.profile
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/thin-performance.profile
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/profile/vdo-small.profile
    - flags:
      - O_CREAT
      - O_EXCL
      - O_RDWR
      path: /etc/lvm/sed5Ci9OW
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/sedGtBvAT
    - flags:
      - O_CREAT
      - O_EXCL
      - O_RDWR
      path: /etc/lvm/sedXfS5lX
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/sedbevB9S
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/sedh82U1c
    - flags:
      - O_EXCL
      - O_RDWR
      - O_CREAT
      path: /etc/lvm/sedwPolu0
    - flags:
      - O_RDWR
      - O_CREAT
      - O_EXCL
      path: /etc/lvm/sedwek82i
    - flags:
      - O_CREAT
      - O_EXCL
      - O_RDWR
      path: /etc/lvm/sedxmzepa
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /gce-pd-csi-driver
    - flags:
      - O_RDONLY
      path: /initialize-driver.sh
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libnss_compat.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libselinux.so.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libtinfo.so.6
    - flags:
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      - O_CLOEXEC
      path: /lvm-tmp/lvm
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/lvm.conf
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/lvmlocal.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      path: /lvm-tmp/lvm/profile
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/profile/cache-mq.profile
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/profile/cache-smq.profile
    - flags:
      - O_NOFOLLOW
      - O_RDONLY
      path: /lvm-tmp/lvm/profile/command_profile_template.profile
    - flags:
      - O_NOFOLLOW
      - O_RDONLY
      path: /lvm-tmp/lvm/profile/lvmdbusd.profile
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/profile/metadata_profile_template.profile
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/profile/thin-generic.profile
    - flags:
      - O_RDONLY
      - O_NOFOLLOW
      path: /lvm-tmp/lvm/profile/thin-performance.profile
    - flags:
      - O_NOFOLLOW
      - O_RDONLY
      path: /lvm-tmp/lvm/profile/vdo-small.profile
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      path: /tmp/kubelet-detect-safe-umount3310381331
    - flags:
      - O_RDONLY
      path: /tmp/kubelet-detect-safe-umount3805061794
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libacl.so.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libattr.so.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libblkid.so.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libmount.so.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_00_40.476199739/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_00_40.476199739/token
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_01_12.1428835288/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_01_12.1428835288/token
    rulePolicies:
      R0001:
        processAllowed:
        - cp
        - gce-pd-csi-driv
        - initialize-driv
        - sed
        - umount
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - copy_file_range
    - dup
    - dup2
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat2
    - fadvise64
    - fchown
    - fcntl
    - fgetxattr
    - fsetxattr
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpeername
    - getpgrp
    - getpid
    - getppid
    - getrandom
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - listen
    - lseek
    - madvise
    - mkdir
    - mkdirat
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pidfd_open
    - pidfd_send_signal
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rename
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - statfs
    - sysinfo
    - tgkill
    - umask
    - umount2
    - uname
    - unlinkat
    - wait4
    - waitid
    - write
  - capabilities:
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /csi-node-driver-registrar
      - --v=5
      - --csi-address=/csi/csi.sock
      - --kubelet-registration-path=/var/lib/kubelet/plugins/pd.csi.storage.gke.io/csi.sock
      path: /csi-node-driver-registrar
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/csi-node-driver-registrar@sha256:4ae50172740cc284e41b6c18786da645b2df60d1721759d3e9b9c1a108c95a77
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/csi-node-driver-registrar@sha256:4ae50172740cc284e41b6c18786da645b2df60d1721759d3e9b9c1a108c95a77
    name: csi-driver-registrar
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /csi-node-driver-registrar
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    rulePolicies:
      R0001:
        processAllowed:
        - csi-node-driver
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clock_nanosleep
    - clone
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat2
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - kill
    - listen
    - lseek
    - madvise
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - openat
    - pipe2
    - poll
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendto
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - socketpair
    - statfs
    - tgkill
    - umask
    - uname
    - unlinkat
    - wait4
    - write
status: {}
