apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-ReplicaSet/name-konnectivity-agent-autoscaler-765c6d6d4b
    kubescape.io/resource-size: "73"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/deployment-konnectivity-agent-autoscaler
  creationTimestamp: "2025-12-14T20:03:52Z"
  labels:
    kubescape.io/instance-template-hash: 765c6d6d4b
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: konnectivity-agent-autoscaler
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765742321079455004"
  name: replicaset-konnectivity-agent-autoscaler-765c6d6d4b
  namespace: kube-system
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /cluster-proportional-autoscaler
      - --namespace=kube-system
      - --configmap=konnectivity-agent-autoscaler-config
      - --target=deployment/konnectivity-agent
      - --logtostderr=true
      - --v=2
      path: /cluster-proportional-autoscaler
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:4c3e38f0e795196aa85d7c2a98e5d16ec416bd153ebcde51dd305e79d20ca2f6
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:4c3e38f0e795196aa85d7c2a98e5d16ec416bd153ebcde51dd305e79d20ca2f6
    name: autoscaler
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /cluster-proportional-autoscaler
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_19_58_38.3814953569/ca.crt
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_19_58_38.3814953569/token
    rulePolicies:
      R0001:
        processAllowed:
        - cluster-proport
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - faccessat2
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - listen
    - madvise
    - mmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - uname
    - write
status: {}
