apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-ReplicaSet/name-l7-default-backend-bd7b999b4
    kubescape.io/resource-size: "69"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/deployment-l7-default-backend
  creationTimestamp: "2025-12-14T20:03:21Z"
  labels:
    kubescape.io/instance-template-hash: bd7b999b4
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: l7-default-backend
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765742288844959021"
  name: replicaset-l7-default-backend-bd7b999b4
  namespace: kube-system
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - NET_ADMIN
    endpoints:
    - direction: inbound
      endpoint: :8080/healthz
      headers:
        Connection:
        - close
        Host:
        - 10.1.1.73:8080
      internal: false
      methods:
      - GET
    execs:
    - args:
      - /404-server-with-metrics
      path: /404-server-with-metrics
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/ingress-gce-404-server-with-metrics@sha256:2bb9d17a3eb824516a2c2152479e5506e7618eaaba2ac8d02b52889a460755cb
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/ingress-gce-404-server-with-metrics@sha256:2bb9d17a3eb824516a2c2152479e5506e7618eaaba2ac8d02b52889a460755cb
    name: default-http-backend
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /404-server-with-metrics
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/mountinfo
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    rulePolicies:
      R0001:
        processAllowed:
        - 404-server-with
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - faccessat2
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getpid
    - getppid
    - getsockname
    - gettid
    - listen
    - madvise
    - mmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - statfs
    - tgkill
    - uname
    - write
status: {}
