apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-ReplicaSet/name-kube-dns-7bb4d7f95
    kubescape.io/resource-size: "120"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/deployment-kube-dns
  creationTimestamp: "2025-12-14T18:01:16Z"
  labels:
    kubescape.io/instance-template-hash: 7bb4d7f95
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: kube-dns
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765718795230911022"
  name: replicaset-kube-dns-7bb4d7f95
  namespace: kube-system
  resourceVersion: "8"
spec:
  architectures:
  - amd64
  containers:
  - capabilities: null
    endpoints:
    - direction: inbound
      endpoint: :10054/healthcheck/kubedns
      headers:
        Connection:
        - close
        Host:
        - 10.1.3.83:10054
        - 10.1.3.79:10054
      internal: false
      methods:
      - GET
    - direction: inbound
      endpoint: :10054/healthcheck/dnsmasq
      headers:
        Connection:
        - close
        Host:
        - 10.1.3.79:10054
        - 10.1.3.83:10054
      internal: false
      methods:
      - GET
    - direction: inbound
      endpoint: :10054/metrics
      headers:
        Accept-Encoding:
        - gzip
        Connection:
        - close
        Host:
        - 10.1.3.83:10054
        - 127.0.0.1:10054
        - 10.1.3.79:10054
      internal: false
      methods:
      - GET
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-sidecar@sha256:80a8b500dd2bffc477f71ba5dfc1058ac8fe5a73682d2f413e86c87eafb2cb33
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-sidecar@sha256:80a8b500dd2bffc477f71ba5dfc1058ac8fe5a73682d2f413e86c87eafb2cb33
    name: sidecar
    opens:
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/limits
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/netstat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/stat
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - close
    - connect
    - epoll_ctl
    - epoll_pwait
    - fcntl
    - futex
    - getpeername
    - getpid
    - getrandom
    - getsockname
    - madvise
    - nanosleep
    - newfstatat
    - openat
    - read
    - rt_sigreturn
    - sched_yield
    - setsockopt
    - socket
    - statfs
    - tgkill
    - write
  - capabilities: null
    endpoints:
    - direction: outbound
      endpoint: :10055/metrics
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 127.0.0.1:10055
      internal: false
      methods:
      - GET
    - direction: outbound
      endpoint: :10054/metrics
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 127.0.0.1:10054
      internal: false
      methods:
      - GET
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metrics-collector@sha256:ec164c7e60389f0cdb257acc313034f20335ab67be10b0d3b55a30094e678389
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metrics-collector@sha256:ec164c7e60389f0cdb257acc313034f20335ab67be10b0d3b55a30094e678389
    name: kubedns-metrics-collector
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/netstat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/snmp
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - close
    - epoll_ctl
    - epoll_pwait
    - fcntl
    - fstat
    - futex
    - getpid
    - nanosleep
    - openat
    - read
    - rt_sigreturn
    - sched_yield
    - tgkill
    - write
  - capabilities: null
    endpoints:
    - direction: inbound
      endpoint: :8081/readiness
      headers:
        Connection:
        - close
        Host:
        - 10.1.3.79:8081
        - 10.1.3.83:8081
      internal: false
      methods:
      - GET
    - direction: inbound
      endpoint: :10055/metrics
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - 127.0.0.1:10055
      internal: false
      methods:
      - GET
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-kube-dns@sha256:9d10070451a7dc65bbc0aa5c65e66ed37f486b73dfec0596292856a9eae1034f
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-kube-dns@sha256:9d10070451a7dc65bbc0aa5c65e66ed37f486b73dfec0596292856a9eae1034f
    name: kubedns
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /kube-dns-config
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /kube-dns-config/..2025_12_14_13_25_42.2507767185
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /kube-dns-config/..2025_12_14_13_25_42.3145141255
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/limits
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/net/netstat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/stat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_17_27_53.3336033460/token
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_17_29_27.3626900033/token
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - close
    - epoll_ctl
    - epoll_pwait
    - fcntl
    - fstat
    - futex
    - getdents64
    - getpid
    - getrandom
    - getsockname
    - madvise
    - nanosleep
    - newfstatat
    - openat
    - read
    - recvmsg
    - rt_sigreturn
    - sched_yield
    - sendmsg
    - setsockopt
    - statfs
    - tgkill
    - write
  - capabilities: null
    endpoints: null
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-dnsmasq-nanny@sha256:8072e7beed1988d1a65b0ed5ae1f1a4e5d5cb71b3bb3aaff632a71f4ec81423f
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/k8s-dns-dnsmasq-nanny@sha256:8072e7beed1988d1a65b0ed5ae1f1a4e5d5cb71b3bb3aaff632a71f4ec81423f
    name: dnsmasq
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/k8s/dns/dnsmasq-nanny
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/k8s/dns/dnsmasq-nanny/..2025_12_14_13_25_42.2507767185
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/k8s/dns/dnsmasq-nanny/..2025_12_14_13_25_42.3145141255
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - close
    - epoll_ctl
    - epoll_pwait
    - fcntl
    - futex
    - getdents64
    - getpid
    - ioctl
    - nanosleep
    - newfstatat
    - openat
    - pidfd_send_signal
    - poll
    - read
    - recvfrom
    - recvmsg
    - rt_sigreturn
    - sched_yield
    - sendmsg
    - sendto
    - socket
    - tgkill
    - write
    - writev
status: {}
