apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-ReplicaSet/name-antrea-controller-horizontal-autoscaler-5f5c75ffd
    kubescape.io/resource-size: "73"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/deployment-antrea-controller-horizontal-autoscaler
  creationTimestamp: "2025-12-14T20:13:30Z"
  labels:
    kubescape.io/instance-template-hash: 5f5c75ffd
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: antrea-controller-horizontal-autoscaler
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765742898811663017"
  name: replicaset-antrea-controller-horizontal-autoscaler-5f5c75ffd
  namespace: kube-system
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /cluster-proportional-autoscaler
      - --namespace=kube-system
      - --configmap=antrea-controller-horizontal-autoscaler
      - --target=deployment/antrea-controller
      - --nodelabels=kubernetes.io/os=windows
      - --logtostderr=true
      - --v=2
      path: /cluster-proportional-autoscaler
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:af852676a9858afc2842969fb5a204b41368ba41e4f314da179a01b633f64b25
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:af852676a9858afc2842969fb5a204b41368ba41e4f314da179a01b633f64b25
    name: autoscaler
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /cluster-proportional-autoscaler
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_08_17.2635276038/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_20_08_17.2635276038/token
    rulePolicies:
      R0001:
        processAllowed:
        - cluster-proport
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - faccessat2
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - listen
    - madvise
    - mmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - read
    - readlinkat
    - recvfrom
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - uname
    - write
status: {}
