apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-kube-system/kind-ReplicaSet/name-antrea-controller-horizontal-autoscaler-788d8644f5
    kubescape.io/resource-size: "16"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-kube-system/deployment-antrea-controller-horizontal-autoscaler
  creationTimestamp: "2025-12-14T18:01:17Z"
  labels:
    kubescape.io/instance-template-hash: 788d8644f5
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: antrea-controller-horizontal-autoscaler
    kubescape.io/workload-namespace: kube-system
    kubescape.io/workload-resource-version: "1765718754657455017"
  name: replicaset-antrea-controller-horizontal-autoscaler-788d8644f5
  namespace: kube-system
  resourceVersion: "2"
spec:
  architectures:
  - amd64
  containers:
  - capabilities: null
    endpoints: null
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:af852676a9858afc2842969fb5a204b41368ba41e4f314da179a01b633f64b25
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/cluster-proportional-autoscaler@sha256:af852676a9858afc2842969fb5a204b41368ba41e4f314da179a01b633f64b25
    name: autoscaler
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/..2025_12_14_17_29_17.3286012070/token
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - close
    - epoll_ctl
    - epoll_pwait
    - fcntl
    - fstat
    - futex
    - getpid
    - getrandom
    - nanosleep
    - openat
    - read
    - rt_sigreturn
    - sched_yield
    - tgkill
    - write
status: {}
