apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: cert-provisioner-job-provisioner
  namespace: pl
  annotations: {kubescape.io/managed-by: User}
spec:
  execs:
  - path: /app/src/utils/cert_provisioner/cert_provisioner.runfiles/px/src/utils/cert_provisioner/cert_provisioner_/cert_provisioner
    args: [/app/src/utils/cert_provisioner/cert_provisioner]
    envs: []
    argsrequired: false
  opens:
  - path: /app/src/utils/cert_provisioner/cert_provisioner.runfiles/px/bazel-out/k8-opt/bin/external/io_bazel_rules_go/stdlib_/lib/time/zoneinfo.zip
    flags: [O_RDONLY]
  - path: /app/src/utils/cert_provisioner/cert_provisioner.runfiles/px/src/utils/cert_provisioner/cert_provisioner_/cert_provisioner
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/ld.so.cache
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/localtime
    flags: [O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libc.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libresolv.so.2
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/maps"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/task/*"
    flags: [O_CLOEXEC, O_DIRECTORY, O_RDONLY]
  - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    flags: [O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/ca.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/token"
    flags: [O_CLOEXEC, O_RDONLY]
  capabilities: [CAP_DAC_OVERRIDE, CAP_DAC_READ_SEARCH]
