apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: vizier-query-broker
  namespace: pl
  annotations: {kubescape.io/managed-by: User}
spec:
  execs:
  - path: /app/src/vizier/services/query_broker/query_broker.runfiles/px/src/vizier/services/query_broker/query_broker_/query_broker
    args: [/app/src/vizier/services/query_broker/query_broker]
    envs: []
    argsrequired: false
  opens:
  - path: /app/src/vizier/services/query_broker/query_broker.runfiles/px/bazel-out/k8-opt/bin/external/io_bazel_rules_go/stdlib_/lib/time/zoneinfo.zip
    flags: [O_RDONLY]
  - path: /app/src/vizier/services/query_broker/query_broker.runfiles/px/src/vizier/services/query_broker/query_broker_/query_broker
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/certs/\u22EF/ca.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/certs/\u22EF/client.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/certs/\u22EF/client.key"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/certs/\u22EF/server.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/certs/\u22EF/server.key"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/host.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/hosts
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/ld.so.cache
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/localtime
    flags: [O_RDONLY]
  - path: /etc/nsswitch.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/resolv.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libc.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/liblzma.so.5.4.1
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libresolv.so.2
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libz.so.1.2.13
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/maps"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/net/*"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/task/*"
    flags: [O_CLOEXEC, O_DIRECTORY, O_RDONLY]
  - path: /sys/devices/*
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    flags: [O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/tls/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/tls/x86_64/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/x86_64/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /usr/lib/x86_64-linux-gnu/x86_64/x86_64/libunwind.so.8
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/ca.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/token"
    flags: [O_CLOEXEC, O_RDONLY]
  capabilities: [CAP_FOWNER, CAP_NET_ADMIN]
  egress:
  - identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    podSelector:
      matchLabels: {k8s-app: kube-dns}
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: kube-system}
    ports:
    - {name: UDP-53, protocol: UDP, port: 53}
  - identifier: d9bcc711b1fbffffc6fe9bdacd6057f0b6c5d58863f85bded6d7fb18c18bd077
    podSelector:
      matchLabels: {app: pl-monitoring, component: vizier, name: vizier-metadata}
    ports:
    - {name: TCP-50400, protocol: TCP, port: 50400}
  - identifier: a08590764670db9042dbda79f3deaa0eee333ec6950ccadc5dd0262fcd994e42
    podSelector:
      matchLabels: {app: pl-monitoring, name: pl-nats}
    ports:
    - {name: TCP-4222, protocol: TCP, port: 4222}
  ingress:
  - identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
    ipAddress: 10.42.0.1
    ports:
    - {name: TCP-50300, protocol: TCP, port: 50300}
  - identifier: 47a42bd64869e8ed568c98f218ab5d89ea818764568dffb66fe316abd30926cf
    ipAddress: 10.42.1.0
    ports:
    - {name: TCP-50300, protocol: TCP, port: 50300}
  - identifier: 62ee591d43b945c22a6b4d20155af717cb843a2b85b56ded1939857603480152
    podSelector:
      matchLabels: {app: pl-monitoring, component: vizier, name: kelvin, plane: data, vizier-name: pixie}
    ports:
    - {name: TCP-50300, protocol: TCP, port: 50300}
  - identifier: c46150dd8f613da582a6de01611c631d866f1f6566191aa88f5807ec76f2c26e
    podSelector:
      matchLabels: {app: pl-monitoring, cluster-id: 6a59ca82-ebaa-4bcd-88b2-41ae2678d72f, component: vizier, name: vizier-cloud-connector, plane: control, vizier-bootstrap: 'true', vizier-name: pixie}
    ports:
    - {name: TCP-50300, protocol: TCP, port: 50300}
