apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: flux-image-reflector-controller
  namespace: flux-system
  annotations: {kubescape.io/managed-by: User}
spec:
  architectures: [amd64]
  imageID: ghcr.io/fluxcd/image-reflector-controller@sha256:a47e09e024a9ff2ea4f3878a1b90c2850134cfdc8b292ec52268dbc1e57e1a4c
  imageTag: ghcr.io/fluxcd/image-reflector-controller:v1.2.3
  execs:
  - args: [/usr/local/bin/image-reflector-controller, '--events-addr=http://notification-controller.flux-system.svc.cluster.local./', --watch-all-namespaces, --log-level=info, --log-encoding=json, --enable-leader-election]
    path: /usr/local/bin/image-reflector-controller
  opens:
  - flags: [O_RDONLY]
    path: /etc/localtime
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/⋯/cgroup
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/⋯/mountinfo
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/⋯/net/*
  - flags: [O_CLOEXEC, O_DIRECTORY, O_RDONLY]
    path: /proc/⋯/task/*
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /run/secrets/kubernetes.io/serviceaccount/..2026_08_02_18_31_04.1831905725/ca.crt
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /run/secrets/kubernetes.io/serviceaccount/..2026_08_02_18_31_04.1831905725/namespace
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /run/secrets/kubernetes.io/serviceaccount/..2026_08_02_18_31_04.1831905725/token
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /sys/fs/cgroup/*
  - flags: [O_RDONLY]
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /usr/local/bin/image-reflector-controller
  capabilities: [CAP_DAC_OVERRIDE, CAP_DAC_READ_SEARCH, CAP_NET_ADMIN]
  syscalls: [fsync, ftruncate, lseek, mmap, prctl, renameat]
  endpoints:
  - direction: inbound
    endpoint: :9440/readyz
    headers:
      Connection: [close]
      Host: ['*:9440']
    internal: true
    methods: [GET]
  - direction: inbound
    endpoint: :9440/healthz
    headers:
      Connection: [close]
      Host: ['*:9440']
    internal: true
    methods: [GET]
  rulePolicies: {}
  matchLabels: {app: image-reflector-controller}
  ingress: null
  egress:
  - identifier: dd18fa52244005a49761004e6173ec450c0779087cedb1eaf1ae49142a6550a2
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: default}
    podSelector:
      matchLabels: {component: apiserver, provider: kubernetes}
    ports:
    - {name: TCP-443, port: 443, protocol: TCP}
    type: internal
