apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-batch/v1/namespace-px-operator/kind-Job/name-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b/initContainerName-pull
    kubescape.io/otel-span-id: ""
    kubescape.io/otel-traceparent: ""
    kubescape.io/resource-size: "85"
    kubescape.io/status: completed
    kubescape.io/sync-checksum: d12e1dff5508a1bde01f008e0150117f893788bacf2f97d9c62a77e5e952a8ab
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-px-operator/job-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
    kubescape.io/workload-container-type: initContainers
  creationTimestamp: "2026-08-22T07:22:00Z"
  labels:
    kubescape.io/learning-period: 2h
    kubescape.io/workload-api-group: batch
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-container-name: pull
    kubescape.io/workload-kind: Job
    kubescape.io/workload-name: 23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
    kubescape.io/workload-namespace: px-operator
    kubescape.io/workload-resource-version: "24782"
  name: job-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b-pull-8af0-18cc
  namespace: px-operator
  resourceVersion: "1"
spec:
  architectures:
  - amd64
  capabilities: null
  egress: null
  endpoints: null
  execs:
  - args:
    - /util/cpb
    - /bundle
    path: /util/cpb
  identifiedCallStacks: null
  imageID: gcr.io/pixie-oss/pixie-prod/operator/bundle@sha256:4c8ddd61d02a1b51a440c975aeff2d7ca174637cb8d7b1ece4281daa7b5a18ff
  imageTag: gcr.io/pixie-oss/pixie-prod/operator/bundle:0.1.7
  ingress: null
  matchLabels:
    batch.kubernetes.io/controller-uid: 784b463a-e418-4e72-9e8e-05de7b6e8537
  opens:
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /bundle
  - flags:
    - O_RDWR
    - O_CREAT
    - O_TRUNC
    - O_CLOEXEC
    path: /bundle/manifests/crd.yaml
  - flags:
    - O_TRUNC
    - O_CLOEXEC
    - O_RDWR
    - O_CREAT
    path: /bundle/manifests/csv.yaml
  - flags:
    - O_RDWR
    - O_CREAT
    - O_TRUNC
    - O_CLOEXEC
    path: /bundle/metadata/annotations.yaml
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /dev
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /etc
  - flags:
    - O_RDONLY
    path: /etc/localtime
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /manifests
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /manifests/crd.yaml
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /manifests/csv.yaml
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /metadata
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /metadata/annotations.yaml
  - flags:
    - O_RDONLY
    path: /opt/hostedtoolcache/go/1.21.7/x64/lib/time/zoneinfo.zip
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /proc/⋯/task/1/fd
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /sys
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /util
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /util/cpb
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var/run
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var/run/secrets
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var/run/secrets/kubernetes.io
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var/run/secrets/kubernetes.io/serviceaccount
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /var/run/secrets/kubernetes.io/serviceaccount/..2026_08_22_07_21_13.2786146484
  rulePolicies: {}
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls:
  - arch_prctl
  - brk
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - copy_file_range
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit
  - exit_group
  - faccessat2
  - fchmodat
  - fcntl
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getpid
  - getppid
  - getrlimit
  - gettid
  - madvise
  - mkdirat
  - mmap
  - munmap
  - nanosleep
  - newfstatat
  - openat
  - openat2
  - pipe2
  - prctl
  - pread64
  - read
  - readlinkat
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - setgid
  - setgroups
  - setuid
  - sigaltstack
  - statfs
  - statx
  - tgkill
  - tkill
  - uname
  - unknown
  - write
status: {}
