apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
    name: replicaset-dynatrace-operator-5d9b4d586d
    namespace: dynatrace
    annotations:
        kubescape.io/completion: complete
        kubescape.io/instance-id: apiVersion-apps/v1/namespace-dynatrace/kind-ReplicaSet/name-dynatrace-operator-5d9b4d586d
        kubescape.io/resource-size: "115"
        kubescape.io/status: completed
        kubescape.io/wlid: wlid://cluster-bobexample/namespace-dynatrace/deployment-dynatrace-operator
    labels:
        kubescape.io/instance-template-hash: 5d9b4d586d
        kubescape.io/workload-api-group: apps
        kubescape.io/workload-api-version: v1
        kubescape.io/workload-kind: Deployment
        kubescape.io/workload-name: dynatrace-operator
        kubescape.io/workload-namespace: dynatrace
        kubescape.io/workload-resource-version: "5438"
spec:
    architectures:
        - amd64
    containers:
        - name: operator
          imageTag: public.ecr.aws/dynatrace/dynatrace-operator:v1.6.1
          capabilities:
            - CHOWN
            - DAC_OVERRIDE
            - DAC_READ_SEARCH
            - NET_ADMIN
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_ADMIN
          endpoints:
            - direction: inbound
              endpoint: :10080/livez
              headers:
                Connection:
                    - close
                Host:
                    - 10.244.1.12:10080
              internal: false
              methods:
                - GET
          execs:
            - path: /usr/local/bin/entrypoint
              args:
                - /usr/local/bin/entrypoint
                - operator
            - path: /usr/local/bin/dynatrace-operator
              args:
                - /usr/local/bin/dynatrace-operator
                - operator
            - path: /usr/local/bin/dynatrace-operator
              args:
                - /usr/local/bin/dynatrace-operator
                - startup-probe
          opens:
            - path: /etc/hosts
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /etc/ld.so.cache
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /etc/nsswitch.conf
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /etc/passwd
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /etc/resolv.conf
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/kernel/cap_last_cap
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/maps
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/mountinfo
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/net/core/somaxconn
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/setgroups
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/task/1/fd
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /proc/⋯/task/14/fd
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /run/secrets/kubernetes.io/serviceaccount/..2025_08_07_15_58_21.2743558122/ca.crt
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /run/secrets/kubernetes.io/serviceaccount/..2025_08_07_15_58_21.2743558122/token
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
              flags:
                - O_RDONLY
            - path: /usr/lib64/libc.so.6
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /usr/lib64/libtinfo.so.6.2
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /usr/local/bin/dynatrace-operator
              flags:
                - O_CLOEXEC
                - O_RDONLY
            - path: /usr/local/bin/entrypoint
              flags:
                - O_RDONLY
          syscalls:
            - accept4
            - access
            - arch_prctl
            - bind
            - brk
            - capget
            - capset
            - chdir
            - clone
            - clone3
            - close
            - close_range
            - connect
            - dup2
            - epoll_create1
            - epoll_ctl
            - epoll_pwait
            - eventfd2
            - execve
            - exit
            - exit_group
            - faccessat2
            - fchown
            - fcntl
            - fstat
            - fstatfs
            - futex
            - getcwd
            - getdents64
            - getegid
            - geteuid
            - getgid
            - getpeername
            - getpgrp
            - getpid
            - getppid
            - getrandom
            - getrlimit
            - getsockname
            - getsockopt
            - gettid
            - getuid
            - ioctl
            - keyctl
            - listen
            - lseek
            - madvise
            - mmap
            - mprotect
            - munmap
            - nanosleep
            - newfstatat
            - openat
            - pipe2
            - prctl
            - pread64
            - prlimit64
            - read
            - readlinkat
            - recvfrom
            - rseq
            - rt_sigaction
            - rt_sigprocmask
            - rt_sigreturn
            - sched_getaffinity
            - sched_yield
            - set_robust_list
            - set_tid_address
            - setgid
            - setgroups
            - setns
            - setrlimit
            - setsid
            - setsockopt
            - setuid
            - sigaltstack
            - socket
            - statfs
            - sysinfo
            - tgkill
            - uname
            - unshare
            - write
