apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly-client
  namespace: dragonfly
  labels:
    app: dragonfly-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly-client
  template:
    metadata:
      labels:
        app: dragonfly-client
        kubescape.io/user-defined-profile: dragonfly-client
    spec:
      containers:
        - name: client
          image: redis:7-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              i=0
              while true; do
                redis-cli -h dragonfly -p 6379 SET "k:$i" "v:$i" >/dev/null
                i=$((i+1)); sleep 2
              done
          resources:
            requests: { cpu: 25m, memory: 32Mi }
            limits: { cpu: 250m, memory: 128Mi }
