apiVersion: v1
kind: Namespace
metadata:
  name: redis-oss
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-oss
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    dir /data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis-oss
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/version: "8.10.0"
        bob.k8sstormcenter.io/distro: redis-oss
        kubescape.io/user-defined-profile: redis
    spec:
      containers:
        - name: redis
          image: redis:8.10.0
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_PTRACE"]
              drop: ["NET_RAW"]
          volumeMounts:
            - name: config
              mountPath: /etc/redis
            - name: data
              mountPath: /data
            - name: host-etc
              mountPath: /host-etc
              readOnly: true
            - name: host-tmp
              mountPath: /host-tmp
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: data
          emptyDir: {}
        - name: host-etc
          hostPath:
            path: /etc
            type: Directory
        - name: host-tmp
          hostPath:
            path: /tmp
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-oss
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
  namespace: redis-oss
  labels:
    app.kubernetes.io/name: redis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-client
    spec:
      containers:
        - name: client
          image: redis:8.10.0-alpine
          command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-client
  namespace: redis-oss
spec:
  selector:
    app.kubernetes.io/name: redis-client
  ports:
    - name: client
      port: 6379
      targetPort: 6379
