apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-log4j-poc/kind-ReplicaSet/name-chain-postgres-fcd9d54b7
    kubescape.io/resource-size: "169"
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 021c088148865a1865c23ce08ea226dee888c9b6895bbc42257750752dfcf937
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-log4j-poc/deployment-chain-postgres
  creationTimestamp: "2026-06-17T15:41:29Z"
  labels:
    kubescape.io/instance-template-hash: fcd9d54b7
    kubescape.io/learning-period: 2m
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: chain-postgres
    kubescape.io/workload-namespace: log4j-poc
    kubescape.io/workload-resource-version: "148936"
  name: replicaset-chain-postgres-fcd9d54b7
  namespace: log4j-poc
  resourceVersion: "1"
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CAP_SETGID
    - CAP_SETPCAP
    - CAP_SETUID
    - CAP_SYS_ADMIN
    endpoints: null
    execs:
    - args:
      - /usr/bin/psql
      - -U
      - postgres
      - -d
      - appdb
      - -At
      - -c
      - SELECT 'orders='||count(*) FROM orders;
      path: /usr/bin/psql
    - args:
      - /usr/lib/postgresql/15/bin/psql
      - -U
      - postgres
      - -d
      - appdb
      - -At
      - -c
      - SELECT 'orders='||count(*) FROM orders;
      path: /usr/lib/postgresql/15/bin/psql
    - args:
      - /usr/bin/psql
      - -U
      - postgres
      - -d
      - appdb
      - -At
      - -c
      - SELECT 'orders(+8s)='||count(*) FROM orders;
      path: /usr/bin/psql
    - args:
      - /usr/lib/postgresql/15/bin/psql
      - -U
      - postgres
      - -d
      - appdb
      - -At
      - -c
      - SELECT 'orders(+8s)='||count(*) FROM orders;
      path: /usr/lib/postgresql/15/bin/psql
    identifiedCallStacks: null
    imageID: docker.io/library/postgres@sha256:b395c9b05a57a43c079691104bc8468ea336a42e6148f44095e66d0c056cdd1c
    imageTag: docker.io/library/postgres:15-bookworm
    name: postgres
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /697/setgroups
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /742/setgroups
    - flags:
      - O_RDWR
      path: /apshotter.v1.overlayfs/snapshots/390/fs/var/lib/dpkg/info/libffi8:amd64.md5sums
    - flags:
      - O_RDWR
      path: /apshotter.v1.overlayfs/snapshots/401/fs/usr/lib/postgresql/15/lib/bitcode/postgres
    - flags:
      - O_RDONLY
      path: /base/1/pg_internal.init
    - flags:
      - O_RDWR
      path: /base/16384/16410_fsm
    - flags:
      - O_RDWR
      path: /base/16384/16410_vm
    - flags:
      - O_RDWR
      path: /base/16384/2696_fsm
    - flags:
      - O_RDWR
      - O_NOFOLLOW
      - O_CLOEXEC
      path: /dev/shm/PostgreSQL.3353419992
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /dev/urandom
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/group
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ld.so.cache
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/locale.alias
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      path: /etc/postgresql
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/postgresql-common/user_clusters
    - flags:
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      - O_CLOEXEC
      path: /etc/postgresql/15
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/shadow
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/cgroup
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/kernel/cap_last_cap
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_CLOEXEC
      - O_WRONLY
      path: /proc/⋯/task/697/attr/apparmor/exec
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /proc/⋯/task/697/fd
    - flags:
      - O_WRONLY
      - O_CLOEXEC
      path: /proc/⋯/task/742/attr/apparmor/exec
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      - O_DIRECTORY
      path: /proc/⋯/task/742/fd
    - flags:
      - O_RDONLY
      path: /root/.pgpass
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /root/.postgresqlrc
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /runc
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /sys/fs/cgroup/cpu.max
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/locale/locale-archive
    - flags:
      - O_RDONLY
      - O_NONBLOCK
      - O_DIRECTORY
      - O_CLOEXEC
      path: /usr/lib/postgresql
    - flags:
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libcom_err.so.2.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libcrypto.so.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libffi.so.8.1.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libgnutls.so.30.34.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libhogweed.so.6.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.8
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libkeyutils.so.1.10
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/liblber-2.5.so.0.1.8
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0.1.8
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libnettle.so.8.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libpq.so.5.18
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libreadline.so.8.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libresolv.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libssl.so.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libtasn1.so.6.6.3
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libtinfo.so.6.4
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libunistring.so.2.2.0
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/Carp.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/Exporter.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/Exporter/Heavy.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/Fcntl.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/IPC/Open3.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/POSIX.pm
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/perl-base/Socket.pm
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/perl-base/Symbol.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/Tie/Hash.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/auto/Fcntl/Fcntl.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/auto/POSIX/POSIX.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/auto/Socket/Socket.so
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/constant.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/overloading.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/strict.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/warnings.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/perl-base/warnings/register.pm
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en.utf8/LC_MESSAGES/libpq5-18.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en.utf8/LC_MESSAGES/psql-15.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en/LC_MESSAGES/libpq5-18.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en/LC_MESSAGES/psql-15.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en_US.utf8/LC_MESSAGES/libpq5-18.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en_US.utf8/LC_MESSAGES/psql-15.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en_US/LC_MESSAGES/libpq5-18.mo
    - flags:
      - O_RDONLY
      path: /usr/share/locale/en_US/LC_MESSAGES/psql-15.mo
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/share/perl5/PgCommon.pm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/share/postgresql-common/pg_wrapper
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/1249
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/1259
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/2601
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/2603
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/2610
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/1/2616
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/1/PG_VERSION
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/1/pg_filenode.map
    - flags:
      - O_TRUNC
      - O_WRONLY
      - O_CREAT
      path: /var/lib/postgresql/data/base/1/pg_internal.init.662
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/1259
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16386
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16393
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16395
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16398
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16405
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16407
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16410
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/16417
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2601
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2602
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2619
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2619_fsm
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2619_vm
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2654
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2685
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/16384/2696
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/16384/PG_VERSION
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/16384/pg_filenode.map
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/16384/pg_internal.init
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/5/1259
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/base/5/2601
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/5/PG_VERSION
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/5/pg_filenode.map
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/base/5/pg_internal.init
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/global/pg_filenode.map
    - flags:
      - O_RDONLY
      path: /var/lib/postgresql/data/global/pg_internal.init
    - flags:
      - O_CREAT
      - O_TRUNC
      - O_WRONLY
      path: /var/lib/postgresql/data/global/pg_internal.init.662
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/pg_wal/000000010000000000000001
    - flags:
      - O_RDWR
      path: /var/lib/postgresql/data/postmaster.pid
    rulePolicies: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - access
    - arch_prctl
    - brk
    - chdir
    - clone
    - epoll_create1
    - execve
    - exit_group
    - fdatasync
    - getcwd
    - getdents64
    - getegid
    - getgid
    - getrandom
    - getsockname
    - getuid
    - ioctl
    - kill
    - lseek
    - mprotect
    - newfstatat
    - prlimit64
    - pselect6
    - pwrite64
    - readlink
    - rename
    - sendto
    - set_tid_address
    - setitimer
    - setsid
    - signalfd4
    - unlink
status: {}
