apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: chain-backend
  namespace: log4j-poc
spec:
  architectures:
  - amd64
  imageID: ghcr.io/k8sstormcenter/log4j-chain-backend-vulnerable@sha256:8f3cb3f9565c7898972d5141ea86681211045b9dbb54f5aafa17f8e0e7be6bb1
  imageTag: ghcr.io/k8sstormcenter/log4j-chain-backend-vulnerable:2e642e5
  execs:
  - path: /opt/java/openjdk/bin/java
    args:
    - /opt/java/openjdk/bin/java
    - -jar
    - /app/app.jar
  - path: /usr/bin/java
    args:
    - /usr/bin/java
    - -jar
    - /app/app.jar
  - path: /usr/bin/curl
    args:
    - /usr/bin/curl
  - path: /usr/bin/psql
    args:
    - /usr/bin/psql
  - path: /usr/lib/postgresql/18/bin/psql
    args:
    - /usr/lib/postgresql/18/bin/psql
    - ⋯⋯
  opens:
  - path: /app/app.jar
    flags:
    - O_RDONLY
  - path: /etc/localtime
    flags:
    - O_RDONLY
  - path: /etc/resolv.conf
    flags:
    - O_RDONLY
  - path: /etc/hosts
    flags:
    - O_RDONLY
  - path: /etc/nsswitch.conf
    flags:
    - O_RDONLY
  - path: /etc/host.conf
    flags:
    - O_RDONLY
  - path: /etc/passwd
    flags:
    - O_RDONLY
  - path: /etc/group
    flags:
    - O_RDONLY
  - path: /opt/java/openjdk/lib
    flags:
    - O_RDONLY
  - path: /opt/java/openjdk/conf
    flags:
    - O_RDONLY
  - path: /usr/lib/jvm
    flags:
    - O_RDONLY
  - path: /tmp
    flags:
    - O_RDWR
    - O_CREAT
  - path: /proc/sys/net
    flags:
    - O_RDONLY
  - path: /app/BOOT-INF/lib
    flags:
    - O_RDONLY
  - path: /opt/java/openjdk/conf/jndi.properties
    flags:
    - O_RDONLY
  - path: /root/.pgpass
    flags:
    - O_RDONLY
  - path: /usr/lib/x86_64-linux-gnu/perl-base/Symbol.pm
    flags:
    - O_RDONLY
  - path: /usr/lib/x86_64-linux-gnu/perl-base/IPC/Open3.pm
    flags:
    - O_RDONLY
  - path: /usr/lib/x86_64-linux-gnu/perl-base/constant.pm
    flags:
    - O_RDONLY
  - path: /usr/share/perl5/PgCommon.pm
    flags:
    - O_RDONLY
  - path: /usr/share/coreutils/locales/en-US.ftl
    flags:
    - O_RDONLY
  - path: /usr/share/coreutils/locales/head/en-US.ftl
    flags:
    - O_RDONLY
  - path: /usr/share/coreutils/locales/env/en-US.ftl
    flags:
    - O_RDONLY
  - path: /opt/java/openjdk/*
    flags:
    - O_RDONLY
  - path: /etc/ld.so.cache
    flags:
    - O_RDONLY
  - path: /etc/krb5/*
    flags:
    - O_RDONLY
  - path: /etc/gss/*
    flags:
    - O_RDONLY
  - path: /etc/locale.alias
    flags:
    - O_RDONLY
  - path: /etc/ssl/*
    flags:
    - O_RDONLY
  - path: /opt/java/openjdk
    flags:
    - O_RDONLY
  - path: /etc/krb5
    flags:
    - O_RDONLY
  - path: /etc/gss
    flags:
    - O_RDONLY
  - path: /etc/ssl
    flags:
    - O_RDONLY
  seccompProfile:
    spec:
      defaultAction: ''
  endpoints:
  - endpoint: :8080/api/products
    direction: inbound
    methods:
    - GET
    internal: true
  - endpoint: :8080/api/login
    direction: inbound
    methods:
    - POST
    internal: true
  - endpoint: :8080/healthz
    direction: inbound
    methods:
    - GET
    internal: true
  rulePolicies:
    R0002:
      processAllowed:
      - px_jattach
      - Attach Listener
      - C1 CompilerThre
      - C2 CompilerThre
      - runc:[1:INIT]
      - runc:[2:INIT]
      - runc:[3:INIT]
    R0004:
      processAllowed:
      - runc:[1:INIT]
      - runc:[2:INIT]
      - runc:[3:INIT]
  matchLabels:
    app: chain-backend
  ingress:
  - identifier: ingress-from-frontend
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
    podSelector:
      matchLabels:
        app: chain-frontend
    namespaceSelector: null
    type: internal
  - identifier: ingress-from-observer
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
    podSelector:
      matchLabels:
        app: chain-observer
    namespaceSelector: null
    type: internal
  egress:
  - identifier: egress-kube-dns
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    - name: TCP-53
      port: 53
      protocol: TCP
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    type: internal
  - identifier: egress-chain-postgres
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: TCP-5432
      port: 5432
      protocol: TCP
    podSelector:
      matchLabels:
        app: chain-postgres
    namespaceSelector: null
    type: internal
