apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: chain-postgres
  namespace: log4j-poc
spec:
  architectures:
  - amd64
  imageID: docker.io/library/postgres@sha256:54c00787dc4e66a69c51e05cb86eead99a3ff2fc04a98bdce6f5cd1130fdbb56
  imageTag: docker.io/library/postgres:15-bookworm
  capabilities:
  - CAP_CHOWN
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_FOWNER
  - CAP_FSETID
  - CAP_KILL
  - CAP_SETGID
  - CAP_SETUID
  execs:
  - path: /usr/lib/postgresql/16/bin/postgres
    args:
    - postgres
  - path: /usr/lib/postgresql/16/bin/initdb
    args:
    - initdb
  - path: /usr/local/bin/docker-entrypoint.sh
    args:
    - /usr/local/bin/docker-entrypoint.sh
    - postgres
  - path: /usr/bin/psql
    args:
    - /usr/bin/psql
  - path: /usr/lib/postgresql/16/bin/pg_isready
    args:
    - pg_isready
  opens:
  - path: /var/lib/postgresql/data
    flags:
    - O_RDWR
    - O_CREAT
  - path: /etc/passwd
    flags:
    - O_RDONLY
  - path: /etc/group
    flags:
    - O_RDONLY
  - path: /etc/resolv.conf
    flags:
    - O_RDONLY
  - path: /etc/hosts
    flags:
    - O_RDONLY
  - path: /etc/localtime
    flags:
    - O_RDONLY
  - path: /etc/nsswitch.conf
    flags:
    - O_RDONLY
  - path: /usr/share/postgresql
    flags:
    - O_RDONLY
  - path: /docker-entrypoint-initdb.d
    flags:
    - O_RDONLY
  - path: /tmp
    flags:
    - O_RDWR
    - O_CREAT
  - path: /var/run/postgresql
    flags:
    - O_RDWR
    - O_CREAT
  - path: /var/lib/postgresql/*
    flags:
    - O_RDONLY
  - path: /run/postgresql/*
    flags:
    - O_RDONLY
  - path: /etc/ld.so.cache
    flags:
    - O_RDONLY
  - path: /etc/locale.alias
    flags:
    - O_RDONLY
  - path: /etc/ssl/*
    flags:
    - O_RDONLY
  - path: /etc/gai.conf
    flags:
    - O_RDONLY
  - path: /var/lib/postgresql
    flags:
    - O_RDONLY
  - path: /run/postgresql
    flags:
    - O_RDONLY
  - path: /etc/ssl
    flags:
    - O_RDONLY
  seccompProfile:
    spec:
      defaultAction: ''
  endpoints:
  - endpoint: :5432/
    direction: inbound
    methods: []
    internal: true
  matchLabels:
    app: chain-postgres
  ingress:
  - identifier: ingress-from-backend
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: TCP-5432
      port: 5432
      protocol: TCP
    podSelector:
      matchLabels:
        app: chain-backend
    namespaceSelector: null
    type: internal
  egress:
  - identifier: egress-kube-dns
    ipAddress: ''
    dns: ''
    dnsNames: null
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    - name: TCP-53
      port: 53
      protocol: TCP
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    type: internal
