apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations: {kubescape.io/managed-by: User}
  name: agent-orchestrator-otel-collector
  namespace: agent-system
spec:
  architectures: [amd64]
  capabilities: [CAP_DAC_OVERRIDE, CAP_DAC_READ_SEARCH, CAP_NET_ADMIN, CAP_SYSLOG]
  egress:
  - dns: ''
    dnsNames: null
    identifier: a8cdac00659dafb0d95d977dad974a012ed5b9b7954ba900d6cc2980e08e508e
    ipAddress: 10.43.8.195
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: oopservability}
    podSelector:
      matchLabels: {app: target-allocator}
    ports:
    - {name: TCP-80, port: 80, protocol: TCP}
    type: internal
  - dns: ''
    dnsNames: null
    identifier: 4380bec7cadc8df8f7321e3ceac7739db245e5db032c59fdb73c104aa0543112
    ipAddress: 10.43.0.10
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: kube-system}
    podSelector:
      matchLabels: {k8s-app: kube-dns}
    ports:
    - {name: UDP-53, port: 53, protocol: UDP}
    type: internal
  endpoints:
  - direction: outbound
    endpoint: :80/scrape_configs
    headers:
      Accept-Encoding: [gzip]
      Host: ['target-allocator.oopservability.svc.cluster.local:80']
    internal: true
    methods: [GET]
  execs:
  - args: [/otelcol-contrib, --config=/conf/collector.yaml]
    path: /otelcol-contrib
  - args: [/pause]
    path: /pause
  identifiedCallStacks: null
  imageID: docker.io/otel/opentelemetry-collector-contrib@sha256:d57bfe8eee2378f31cb1193239fbcac521d54a5a071fca2bfc106916a32b892d
  imageTag: docker.io/otel/opentelemetry-collector-contrib:0.151.0
  ingress: null
  matchLabels: {app: agent-orchestrator}
  opens:
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/conf/\u22EF/collector.yaml"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /etc/hosts
  - flags: [O_RDONLY]
    path: /etc/localtime
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /etc/nsswitch.conf
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /etc/resolv.conf
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /otelcol-contrib
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/bus/pci/devices
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/cpuinfo
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/modules
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/stat
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /proc/sys/net/core/somaxconn
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/cgroup"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/environ"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/maps"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/mountinfo"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/stat"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: "/proc/\u22EF/status"
  - flags: [O_CLOEXEC, O_DIRECTORY, O_RDONLY]
    path: "/proc/\u22EF/task/*"
  - flags: [O_CLOEXEC, O_RDONLY]
    path: /sys/fs/cgroup/*
  - flags: [O_RDONLY]
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  rulePolicies: {}
  seccompProfile:
    spec: {defaultAction: ''}
  syscalls: null
status: {}
