apiVersion: v1
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            proxy_pass http://backend:8080;
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
kind: ConfigMap
metadata:
  name: frontend-conf
  namespace: java-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: java-poc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        kubescape.io/user-defined-network: frontend
        kubescape.io/user-defined-profile: frontend
    spec:
      containers:
        - image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: frontend-conf
          name: conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: java-poc
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  type: NodePort
