apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: vizier-operator
  namespace: px-operator
  annotations: {kubescape.io/managed-by: User}
spec:
  execs:
  - path: /app/src/operator/operator.runfiles/px/src/operator/operator_/operator
    args: [/app/src/operator/operator]
    envs: []
    argsrequired: false
  opens:
  - path: /app/src/operator/operator.runfiles/px/GOROOT/lib/time/zoneinfo.zip
    flags: [O_RDONLY]
  - path: /app/src/operator/operator.runfiles/px/src/operator/operator_/operator
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/host.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/hosts
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/ld.so.cache
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/localtime
    flags: [O_RDONLY]
  - path: /etc/nsswitch.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/pki/tls/certs
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/resolv.conf
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/ssl/certs
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /etc/ssl/certs/ca-certificates.crt
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v2/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/glibc-hwcaps/x86-64-v3/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libc.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/libresolv.so.2
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/tls/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: /lib/x86_64-linux-gnu/x86_64/x86_64/libm.so.6
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/net/*"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/proc/\u22EF/task/*"
    flags: [O_CLOEXEC, O_DIRECTORY, O_RDONLY]
  - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    flags: [O_RDONLY]
  - path: /system/etc/security/cacerts
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/ca.crt"
    flags: [O_CLOEXEC, O_RDONLY]
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/token"
    flags: [O_CLOEXEC, O_RDONLY]
  capabilities: [CAP_NET_ADMIN]
  egress:
  - identifier: da8e219b26f6e8ddd6c74e3e35355a97a0528bf150772dbbe21aa771733fe958
    podSelector:
      matchLabels: {app: pl-monitoring, cluster-id: 6a59ca82-ebaa-4bcd-88b2-41ae2678d72f, component: vizier, name: vizier-cloud-connector, plane: control, vizier-bootstrap: 'true', vizier-name: pixie}
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: pl}
    ports:
    - {name: TCP-50800, protocol: TCP, port: 50800}
  - identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    podSelector:
      matchLabels: {k8s-app: kube-dns}
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: kube-system}
    ports:
    - {name: UDP-53, protocol: UDP, port: 53}
  - identifier: 284d617ca3e493147f79f2c7f185037100a9c2636930eec7995122394206e7fe
    ipAddress: 100.103.139.51
    ports:
    - {name: TCP-443, protocol: TCP, port: 443}
  - identifier: 2ecd1f4c02e1461f6029b18d649c33cf593473ef52be42e8826414c52906b784
    podSelector:
      matchLabels: {app: pl-monitoring, name: pl-nats, plane: control, vizier-name: pixie}
    namespaceSelector:
      matchLabels: {kubernetes.io/metadata.name: pl}
    ports:
    - {name: TCP-8222, protocol: TCP, port: 8222}
