package main

import (
	"fmt"
	"sort"
	"strings"
)

// AppArmorConverter converts an ApplicationProfile into an AppArmor profile string.
type AppArmorConverter struct {
	profile *ApplicationProfile
	config  *TemplateConfig
}


func NewAppArmorConverter(profile *ApplicationProfile, config *TemplateConfig) *AppArmorConverter {
	return &AppArmorConverter{profile: profile, config: config}
}

// Full pipeline to convert the ApplicationProfile into an AppArmor profile string
func (c *AppArmorConverter) Convert() string {
	openRules := convertOpensToPathRules(c.profile)
	execRules := convertExecsToPathRules(c.profile)
	mergedPath := mergePathRules(append(openRules, execRules...))
	pathRules := renderPathRules(mergedPath)
	capRules := convertCapToAppArmorRules(c.profile)
	netRules := convertEndpointsToAppArmorRules(c.profile)
	return c.build(pathRules, capRules, netRules)
}

// build assembles the final AppArmor profile 
func (c *AppArmorConverter) build(pathRules, capRules, netRules []string) string {
	var lines []string

	profileName := "bob_generated_profile"
	if c.config != nil && c.config.WorkloadName != "" {
		profileName = c.config.WorkloadName
	}

	lines = append(lines, "#include <tunables/global>")
	lines = append(lines, fmt.Sprintf("profile %s flags=(enforce) {", profileName))
	lines = append(lines, "  #include <abstractions/base>")
	lines = append(lines, "")

	if len(pathRules) > 0 {
		lines = append(lines, "  # File and exec rules from BoB profile")
		lines = append(lines, pathRules...)
		lines = append(lines, "")
	}

	if len(capRules) > 0 {
		lines = append(lines, "  # Capabilities from BoB profile")
		lines = append(lines, capRules...)
		lines = append(lines, "")
	}

	if len(netRules) > 0 {
		lines = append(lines, "  # Endpoint rules from BoB profile")
		lines = append(lines, netRules...)
		lines = append(lines, "")
	}

	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

// --- Path rule types and helpers ---
type MergedPathRule struct {
	Path        string
	Permissions map[rune]bool
	Comments    []string
}

func convertExecsToPathRules(profile *ApplicationProfile) []MergedPathRule {
	var rules []MergedPathRule

	allContainers := append(profile.Spec.Containers, profile.Spec.InitContainers...)

	for _, container := range allContainers {
		for _, execEntry := range container.Execs {
			if strings.HasPrefix(execEntry.Path, "./") {
				// skip paths that are relative
				continue
			}

			// For exec rule, only "ix" permissions are added since we create a apparmor profile per container
			rules = append(rules, MergedPathRule{
				Path: execEntry.Path,
				Permissions: map[rune]bool{
					'i': true,
					'x': true,
				},
				Comments: []string{
					fmt.Sprintf("Container: %s, Exec rule", container.Name),
				},
			})
		}
	}

	return rules
}

func convertOpensToPathRules(profile *ApplicationProfile) []MergedPathRule {
	var rules []MergedPathRule

	allContainers := append(profile.Spec.Containers, profile.Spec.InitContainers...)

	for _, container := range allContainers {
		for _, open := range container.Opens {

			permissions := convertFlagsToAppArmorPermissions(open.Flags)

			// Replace any "⋯" generated by Kubescape with "*" to denote wildcards in AppArmor
			openPath := strings.ReplaceAll(open.Path, "⋯", "*")

			isDir := false
			hasCreate := false
		
			for _, f := range open.Flags {
				switch f {
				case "O_DIRECTORY":
					isDir = true
				case "O_CREAT":
					hasCreate = true
				}
			}

			if isDir && !strings.HasSuffix(openPath, "/") {
				openPath += "/"
			}

			// Give parent directory write permissions if O_CREAT is present and it's not a directory, to allow file creation
			if hasCreate && !isDir {
				parentDir := getParentDirectory(openPath, false)
				rules = append(rules, MergedPathRule{
					Path: parentDir,
					Permissions: map[rune]bool{
						'w': true,
					},
					Comments: []string{
						fmt.Sprintf("Parent dir write for file creation, Container: %s, Original path: %s", container.Name, open.Path),
					},
				})
			}

			permsMap := make(map[rune]bool)
			addPermissions(permsMap, permissions)

			rules = append(rules, MergedPathRule{
				Path:        openPath,
				Permissions: permsMap,
				Comments: []string{
					fmt.Sprintf("Container: %s, Original flags: %v", container.Name, open.Flags),
				},
			})
		}
	}

	return rules
}

// mergePathRules merges rules that share the same path, unioning their permissions.
func mergePathRules(rules []MergedPathRule) []MergedPathRule {
	merged := make(map[string]*MergedPathRule)

	for _, rule := range rules {
		existing, ok := merged[rule.Path]
		if !ok {
			permsCopy := make(map[rune]bool)
			for k, v := range rule.Permissions {
				permsCopy[k] = v
			}
			merged[rule.Path] = &MergedPathRule{
				Path:        rule.Path,
				Permissions: permsCopy,
				Comments:    append([]string{}, rule.Comments...),
			}
			continue
		}

		for p := range rule.Permissions {
			existing.Permissions[p] = true
		}
		existing.Comments = append(existing.Comments, rule.Comments...)
	}

	var result []MergedPathRule
	for _, rule := range merged {
		result = append(result, *rule)
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].Path < result[j].Path
	})

	return result
}

// renderPathRules formats merged path rules as AppArmor profile lines.
func renderPathRules(rules []MergedPathRule) []string {
	var lines []string
	for _, rule := range rules {
		perms := renderPermissions(rule.Permissions)
		lines = append(lines, fmt.Sprintf("  %s %s,", rule.Path, perms))
	}
	return lines
}


// Convert capabilities to AppArmor capability rules
func convertCapToAppArmorRules(profile *ApplicationProfile) []string {
	var rules []string

	allContainers := append(profile.Spec.Containers, profile.Spec.InitContainers...)
	seen := make(map[string]bool)

	for _, container := range allContainers {
		for _, cap := range container.Capabilities {
			capLower := strings.ToLower(cap)
			trimmedCap := strings.TrimPrefix(capLower, "cap_")
			rule := fmt.Sprintf("  capability %s, ", trimmedCap)

			if !seen[rule] {
				rules = append(rules, rule)
				seen[rule] = true
			}
		}
	}
	sort.Strings(rules)
	return rules
}

// This could be enhanced in the future to generate more specific network rules based on the endpoint details, 
// but for now we just add a generic "network" rule if any endpoint is defined.
func convertEndpointsToAppArmorRules(profile *ApplicationProfile) []string {
	var rules []string

	allContainers := append(profile.Spec.Containers, profile.Spec.InitContainers...)
	hasNetworkRules := false

	for _, container := range allContainers {
		for _, endpoint := range container.Endpoints {
			if !hasNetworkRules && endpoint.Endpoint != "" {
				rules = append(rules, "  network ,")
				hasNetworkRules = true
			}
		}
	}

	return rules
}


// Permission helpers 
func addPermissions(m map[rune]bool, perms string) {
	for _, p := range perms {
		m[p] = true
	}
}

func renderPermissions(m map[rune]bool) string {
	order := []rune{'r', 'w', 'i', 'x', 'm', 'k', 'l'}
	var out []rune
	for _, p := range order {
		if m[p] {
			out = append(out, p)
		}
	}
	return string(out)
}

// Helper to convert open flags to AppArmor permissions.
func convertFlagsToAppArmorPermissions(flags []string) string {
	hasRead := false
	hasWrite := false
	hasExecute := false

	for _, flag := range flags {
		switch flag {
		case "O_RDONLY":
			hasRead = true
		case "O_WRONLY":
			hasWrite = true
		case "O_RDWR":
			hasRead = true
			hasWrite = true
		case "O_CREAT", "O_TRUNC", "O_APPEND":
			hasWrite = true
		case "O_EXEC":
			hasExecute = true
		}
	}

	var perms []string
	if hasRead {
		perms = append(perms, "r")
	}
	if hasWrite {
		perms = append(perms, "w")
	}
	if hasExecute {
		perms = append(perms, "x")
	}

	if len(perms) == 0 {
		return "r"
	}

	return strings.Join(perms, "")
}

// Helper to get the parent directory, used when O_CREAT is present to give write permissions to the parent directory for file creation.
func getParentDirectory(path string, isDir bool) string {
	if path == "/" {
		return "/"
	}
	if isDir {
		if !strings.HasSuffix(path, "/") {
			path += "/"
		}
		return path
	}

	path = strings.TrimSuffix(path, "/")
	lastSlash := strings.LastIndex(path, "/")
	if lastSlash == -1 {
		return "/"
	}
	return path[:lastSlash+1]
}