apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    signature.kubescape.io/certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXekNDQVFDZ0F3SUJBZ0lQRDBwbzNRNVA2NmtNVzhKY25OSGJNQW9HQ0NxR1NNNDlCQU1DTUJReEVqQVEKQmdOVkJBTVRDV3h2WTJGc0xXdGxlVEFlRncweU5qQTRNekF3T1RVNE5URmFGdzB5TnpBNE16QXdPVFU0TlRGYQpNQlF4RWpBUUJnTlZCQU1UQ1d4dlkyRnNMV3RsZVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJCWjE0VHZhVjRDUERwZ3lNZkcrVkNnUmNTUVI3TElBN0dpdml5SzVTU2NyMyt2WmN6MEx4VUwvWnNZdkxHYy8KaUtCUE83NGYrNUdJK2lUWHFQTEdHdmlqTlRBek1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBVEJnTlZIU1VFRERBSwpCZ2dyQmdFRkJRY0RBekFNQmdOVkhSTUJBZjhFQWpBQU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ1JqR3lDCjZscnM0eFdtU2E0MnJjUU9kTXV2RXI0L1IydTdOcGFzelRlRXd3SWhBUHd0L3R0ZkRxRXMwelRwR3BEcHowSmkKQTdiS21JRFNLK3paUFRtenMxaDUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    signature.kubescape.io/content: H4sIAAAAAAAA/7xV3W7rNgx+F167ie04ju2rFWkvDnDWFucUw4ahCCiJdoTIkiDJbbMiT7CH2TvtSQbZqXM6bMOwi92EH8UfkZ9o5g3Qyh/IeWk0NOCteF1404YXdMRNb42XQRq9OAyMPEdLC2mWzxmjgBkkcJBaQANbowNKTe7BmVYqggR6CigwIDRvoJCR8hF9SNOjxo7EFTtCA4MnB6cENPYEDUj9TDoYd7xi6CkavCUeU6DjexmIh8GRh+ZnwF6UBTwlwNEik0oGORm21w+7u9vH3fXN95/uogO9Eo+WN7AY9tDA0ljPDDoBCaDrxqjL2dPpKQFjSf9tTKtwCrrffbm5v/v8EyRwv9t+vr/98XYLT6fkEmWd4cvff/1tqSksuXG09KbHV260/o+JAvrDMlu2fyrk5tOX2+3j/ZePKZJL5g/Z/NEvD+Q0qWXfL4ND7S060mG3Hzqy2NFyH393thc7L3+hvyx2ZMofPUelpjfhnGwoRlr5fmcdDwoSYHFcxofqKEzAT2AvpItSGU2T9LPcOdRd1MgapXbcEQbKLvqYesL2BWXMF1/6eQx5HfU2FuQ9hjwqXI8hrQ8Y3mXrIxoCvUICHQX+IiYgSAdfFpNi5fnUzsgp2Y93dBS84YdxgGfN2LMpjP5K+kDxwXsUz3Jsse/RRjHoCWjUxiuiEdPLWNxYZpzEb0DsxEpLozzzax2hGGuN4CyU1IcxzhF/bp3pIww7Lzvk8due1ThZPfrDfOAoDC7aPd+T2HUUsG2lluE4nx0lqXiRp9DJd+DMYP2ELxx4CsPkITtUwQfk8aboMI5A7DNyH7qDVLGZcJYvTgaKn68nHlfS+45p3uadIKjFQYXrqZ8G4HRKgLSwRurgodGDUgnIHjv6dAMNhKAWfj9/yVeMFW26Yfw7v8d8XTZ1XbV52VaVyLOqzKu6WhXEqlVK64q1G1zVuCqI6vUmbVebouJVWRQtq1eCVi3nJZwve8TuH25r8mIfuR4UPRgl+bi23k4JyDhzspUktqjU18jUpQndOfLTRpr9HDRAKacNq7KUsqxiJa9rxli2YvWmZhXPSsHrPCs27YYLRmydU1WvGV9zEnVR5iKNjB/ttHsDOY2RexF3H0zgDnuay7DGhamI88J+3D5c1WmdjlNoguFGTacwOUMTrXFPWCO+kiIejItv12Pg+8/zPwRaCw3MO/Z0/kvwFjldws5c2GshJjYA4lb7QEiZV1lRp7iucyKOrM5bzEsq0lWNFVsXNatWNVWsXFcraokKXBWCRJHWecHr/BtC6PX/I2TK9q9aztJFkS/SRZ5BTEPnwYiOp9MfAQAA///0+lNc2QcAAA==
    signature.kubescape.io/identity: local-key
    signature.kubescape.io/issuer: local
    signature.kubescape.io/signature: MEQCIB3pzdVsRr0dawrx8SUL06tSc61SJ81QITtm1sqQf6TxAiBpTWF8dKb/wLNgQzFWp2x/SBu5wJMhPWBGcSWOaHsvVw==
    signature.kubescape.io/timestamp: "1788083931"
  labels:
    kubescape.io/managed-by: user
  name: inventory-base
  namespace: shop
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_NET_ADMIN
  egress: null
  endpoints: null
  execs:
  - args:
    - /opsboard
    path: /opsboard
  identifiedCallStacks: null
  imageID: ttl.sh/opsboard-bb4f07bc@sha256:998f26f88d2186289834eb830e58bf7a39a34ee9570f3748c8644fb93de3fcc6
  imageTag: ttl.sh/opsboard-bb4f07bc:24h
  ingress:
  - dns: ""
    dnsNames: null
    identifier: e0ce7b810e118b6c99bbb13b979b8c16dc92147f7cdbeb52e895bc5ced9462d0
    ipAddress: ""
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: opsboard
    ports:
    - name: TCP-9090
      port: 9090
      protocol: TCP
    type: internal
  - dns: ""
    dnsNames: null
    identifier: 6281490a592eecab92fa26e4039a8b549b839e8b6583efee4a34ded40924c920
    ipAddress: 10.42.0.21
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-9090
      port: 9090
      protocol: TCP
    type: external
  opens:
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /opsboard
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /proc/⋯/net/core/somaxconn
  - flags:
    - O_DIRECTORY
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/task/1/fd
  - flags:
    - O_RDONLY
    path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  rulePolicies: null
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls:
  - accept4
  - arch_prctl
  - bind
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit
  - faccessat2
  - fcntl
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getpid
  - getppid
  - getrlimit
  - getsockname
  - getsockopt
  - gettid
  - listen
  - madvise
  - mmap
  - munmap
  - nanosleep
  - newfstatat
  - openat
  - openat2
  - pipe2
  - prctl
  - pread64
  - read
  - readlinkat
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - setgid
  - setgroups
  - setsockopt
  - setuid
  - sigaltstack
  - socket
  - statx
  - tgkill
  - tkill
  - write
status: {}
