apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: redis-base
  namespace: shop
  labels:
    kubescape.io/managed-by: user
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_NET_ADMIN
  - CAP_SETGID
  - CAP_SETUID
  execs:
  - args:
    - /usr/bin/id
    - -u
    path: /bin/busybox
  - args:
    - /usr/bin/setpriv
    - --reuid
    - redis
    - --regid
    - redis
    - --clear-groups
    - /usr/local/bin/docker-entrypoint.sh
    - redis-server
    path: /usr/bin/setpriv
  - args:
    - /usr/local/bin/redis-server
    path: /usr/local/bin/redis-server
  - args:
    - /usr/local/bin/docker-entrypoint.sh
    - redis-server
    path: /bin/busybox
  - args:
    - /usr/bin/find
    - .
    - '!'
    - -user
    - redis
    - -exec
    - chown
    - redis
    - '{}'
    - +
    path: /bin/busybox
  opens:
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_DIRECTORY
    - O_CLOEXEC
    path: /data
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /data/dump.rdb
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /dev/urandom
  - flags:
    - O_LARGEFILE
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/group
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /etc/ld-musl-x86_64.path
  - flags:
    - O_RDONLY
    - O_NONBLOCK
    - O_LARGEFILE
    - O_CLOEXEC
    path: /etc/localtime
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_LARGEFILE
    path: /etc/passwd
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /etc/ssl/openssl.cnf
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libcap-ng.so.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libssl.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/net/core/somaxconn
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/stat
  - flags:
    - O_LARGEFILE
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/status
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /proc/⋯/task/1/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    - O_LARGEFILE
    path: /proc/⋯/vm/overcommit_memory
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /sys/devices/system/clocksource/clocksource0/current_clocksource
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /sys/kernel/mm/transparent_hugepage/enabled
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libcap-ng.so.0.0.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libssl.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/bin/docker-entrypoint.sh
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libcap-ng.so.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libssl.so.3
  - path: /data/⋯
    flags:
    - O_WRONLY
    - O_CREAT
    - O_TRUNC
    - O_LARGEFILE
    - O_RDONLY
  - path: /proc/⋯/smaps
    flags:
    - O_RDONLY
    - O_LARGEFILE
  syscalls:
  - accept4
  - arch_prctl
  - bind
  - brk
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - dup2
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit_group
  - faccessat2
  - fcntl
  - fork
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getegid
  - geteuid
  - getgid
  - getpid
  - getppid
  - getrandom
  - getresgid
  - getresuid
  - gettid
  - getuid
  - ioctl
  - listen
  - lseek
  - lstat
  - madvise
  - membarrier
  - mmap
  - mprotect
  - munmap
  - nanosleep
  - newfstatat
  - open
  - openat
  - openat2
  - pipe
  - pipe2
  - prctl
  - prlimit64
  - read
  - readlink
  - readv
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - set_tid_address
  - setgid
  - setgroups
  - setitimer
  - setresgid
  - setresuid
  - setsockopt
  - setuid
  - socket
  - stat
  - statx
  - sysinfo
  - tgkill
  - tkill
  - umask
  - wait4
  - write
  - writev
  ingress:
  - dns: ''
    dnsNames: null
    identifier: 6281490a592eecab92fa26e4039a8b549b839e8b6583efee4a34ded40924c920
    ipAddress: 10.42.0.21
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: external
  - dns: ''
    dnsNames: null
    identifier: 3859b76cbc9306697de2ebfb54c57b486cb712222ef29deca2955df3496cfdb8
    ipAddress: 10.42.1.65
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: external
  imageID: docker.io/library/redis@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
  imageTag: docker.io/library/redis:7-alpine
