apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    signature.kubescape.io/certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYRENDQVFHZ0F3SUJBZ0lRR1BXY0d6cDFYdWUxdVAzcDdFcXVkREFLQmdncWhrak9QUVFEQWpBVU1SSXcKRUFZRFZRUURFd2xzYjJOaGJDMXJaWGt3SGhjTk1qWXdPRE13TURrMU9EUTVXaGNOTWpjd09ETXdNRGsxT0RRNQpXakFVTVJJd0VBWURWUVFERXdsc2IyTmhiQzFyWlhrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUVdkZUU3MmxlQWp3NllNakh4dmxRb0VYRWtFZXl5QU94b3I0c2l1VWtuSzkvcjJYTTlDOFZDLzJiR0x5eG4KUDRpZ1R6dStIL3VSaVBvazE2anl4aHI0b3pVd016QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd013REFZRFZSMFRBUUgvQkFJd0FEQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUEvcXpsCkFKa2VlcjJSeDZ2VG92WGhpODgyUnVrWlk4emY3dnVHQ2c5QWRkQUNJUURSaXI5ZUhCeWlyeGRybFVyZ08zcXIKeFh0Z3p6VnBRd1haL0tBYUw0U1pOUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    signature.kubescape.io/content: H4sIAAAAAAAA/9RX727rug1/lvHrnDhxEifOp3Vtd1Gsaw96evcHQxHQEp0IkSVBktMGRZ7gPsx9p/Mkg+TEbU5Pd9q1X4YgEEWJP5MURZGPgEb8nawTWsEcnOEPfacrf4+WmK6NdsILrfrrpiTH0FBf6HQzLMnjEBJYC8VhDqdaeRSK7BerKyEJEqjJI0ePMH8EiSVJF6gjmBoVLon3yi3MoXFkYZeAwppgDpa4cL0SHQWmM8SCOFq2Ep6Ybyw5mP8bsOb5GO4SYGiwFFJ40S6cnnxZXJ3fLk7O/nZxBUmcfz2//eXi7Gny68VZEKUHYkHmEQz6FcwhLYVKy8ZtS/0ACaBdRsi0cTYuCQ4J9Bq42yVPModFR95YsfmR3NNSr2epiTDRzj1n+R2HSULbW1rdmMCIOFIzlBGNa7Ym2yPl7dZooXzfrQ7iPUd2Q/alhk/iR/u+U/aVXUdo/8VHH9DxJ56vQrgl0IcE/hDPwEXlO5eFo4QE2Erfq2f8xx0k8Ee4290loA2p49OOUZpAJbH92vXi5uz66vJfkMD14vLk5pfzv1xcnsfZ2cXN+ent9U27dnp5ff7P89NjCwJaypva9C0v3wB7LEybtLGouK7fK0qepTFUjgWP9T9onDxBvgCRvFc3TvYeZvkiH/fj0tu880N/RMgQEF7U9CrQ1fXVny+vT//6HlSDzt3zY8gfGPgTnzkn0xgTTvaZqt7rdinK8GdoemrZd7o/+IizDmh2a7wOaKNPQAuWfRTKWM3Sb7/9nq7JKpIpQ7OQ6PyCoXmvyzosRT5l2lLqdI0PTCv1P0M5j/5Dwo37yL3poDy6dTpMK/6qMm9IIR3apk71hizTdS38oqZa2+2rwM91fMVit3UhxQhGLtCe6pRJzdZON5bRc3qQssZaUn7xjPleB4fP7eOlrlNvUTmDEXTVLMngklJSWEp63VuvIMdX5sXNC7+PBPlz1M+5gc8QP+MWvulx/QT0z01qL3E/0bnPcT/DxfH5/vbb78cY/7h5umY35ye3kbq9+fXq++v20wThajTuTeF+l4DbOoZStpUuY2T8OFZFbLUwlnkJCZRtRVTaNcQieEm+JVxLrLgIFRKTWlE7um5cWFTLMOONySABMlrKBbOEnoZP8/idljb3KAJsqLM2FAnhF13ZEXR0Dn0Aq5iKgpWOqlWHDB3GKnqg8RSKvCV5Fp/xJXlOyrt83E729XCgmgPVsUxHdFRXNwWaXLfVkuvk/YFoOUK31knhPIXXRzqidRxbdWvkG+HafqYu0VoRC866js9ebawO3UggG9XyFCrtJFGk6T7aG6FCkbEfunnrKiMM7Yc43R+tsVLUwkd3WEK+H6RQ6z25iSPbVDbabf3CiSWy0LB10xB5Nbp1x7DkGxvWHVsRXyzJY1UJJXx4Whz5hRd8gZxbcq7ltJ4MxKEVceRFqOdsS3feds+87cg7zdba+Hay54akFTmtV8IQosBtnVCVhgT8ci1ksN/vx2avfoi94It7Kzwdxk3o4Byx0Ksems/5Y9cwcqqwkf6k9ckcYLdLgBSP+dLBXDVSJiBqXNLFGcyhzamhOZWitGi3bQf0J7fCbJLPq2qQlZNZVUyHNOVTPpzkOMzyKWWzUcXKkoiK4XQ6KnPEUc7GBUeWzYhVlM0Ieagu47ducfn6x+bTHkoj4n21jaQvWgoW29rHXQIi3BFRCeKnKOVXj2z9ZIdaxlML3U23z8Ic8mw2HBcDnBQZEcOyyCrMchoPRgXOysm4KGejgmZlPpmNqCIa42jMiY8HRTZmRRbSv9+a0JfTgyerMJwLD30UtMQV1tSpYbT1rRL7Zv729EsvH02LGNTaa6Zly4V2M8zDash4RvOvJIl5bQ9oAcMZZPT9gjAn+yidw3DQH2f9QT8bQki7R8aPZpOinOasZMVokOfFlFNGZVVOxmwyLceznJXTYZZlGVVZwYlhVkwmvBqNi5xVvJz9nxg/7OcTCDC0D4Kwcbf7TwAAAP//b/4PCOERAAA=
    signature.kubescape.io/identity: local-key
    signature.kubescape.io/issuer: local
    signature.kubescape.io/signature: MEUCIGqMjinpOI95j5DPY0pyNka3rdpciS7HpkrzP3AdBI6pAiEAwQks4oEuf2meE11QYMIAgd4WR9ewNYRBCJ24q9/v+FI=
    signature.kubescape.io/timestamp: "1788083929"
  labels:
    kubescape.io/managed-by: user
  name: redis-base
  namespace: shop
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_NET_ADMIN
  - CAP_SETGID
  - CAP_SETUID
  egress: null
  endpoints: null
  execs:
  - args:
    - /usr/bin/id
    - -u
    path: /bin/busybox
  - args:
    - /usr/bin/setpriv
    - --reuid
    - redis
    - --regid
    - redis
    - --clear-groups
    - /usr/local/bin/docker-entrypoint.sh
    - redis-server
    path: /usr/bin/setpriv
  - args:
    - /usr/local/bin/redis-server
    path: /usr/local/bin/redis-server
  - args:
    - /usr/local/bin/docker-entrypoint.sh
    - redis-server
    path: /bin/busybox
  - args:
    - /usr/bin/find
    - .
    - '!'
    - -user
    - redis
    - -exec
    - chown
    - redis
    - '{}'
    - +
    path: /bin/busybox
  identifiedCallStacks: null
  imageID: docker.io/library/redis@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
  imageTag: docker.io/library/redis:7-alpine
  ingress:
  - dns: ""
    dnsNames: null
    identifier: 6281490a592eecab92fa26e4039a8b549b839e8b6583efee4a34ded40924c920
    ipAddress: 10.42.0.21
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: external
  - dns: ""
    dnsNames: null
    identifier: 3859b76cbc9306697de2ebfb54c57b486cb712222ef29deca2955df3496cfdb8
    ipAddress: 10.42.1.65
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-6379
      port: 6379
      protocol: TCP
    type: external
  opens:
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_DIRECTORY
    - O_CLOEXEC
    path: /data
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /data/dump.rdb
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /dev/urandom
  - flags:
    - O_LARGEFILE
    - O_CLOEXEC
    - O_RDONLY
    path: /etc/group
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /etc/ld-musl-x86_64.path
  - flags:
    - O_RDONLY
    - O_NONBLOCK
    - O_LARGEFILE
    - O_CLOEXEC
    path: /etc/localtime
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    - O_LARGEFILE
    path: /etc/passwd
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /etc/ssl/openssl.cnf
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libcap-ng.so.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /lib/libssl.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/kernel/cap_last_cap
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/net/core/somaxconn
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/stat
  - flags:
    - O_LARGEFILE
    - O_CLOEXEC
    - O_RDONLY
    path: /proc/⋯/status
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /proc/⋯/task/1/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    - O_LARGEFILE
    path: /proc/⋯/vm/overcommit_memory
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /sys/devices/system/clocksource/clocksource0/current_clocksource
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /sys/kernel/mm/transparent_hugepage/enabled
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libcap-ng.so.0.0.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/lib/libssl.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/bin/docker-entrypoint.sh
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libcap-ng.so.0
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libcrypto.so.3
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    - O_CLOEXEC
    path: /usr/local/lib/libssl.so.3
  - flags:
    - O_WRONLY
    - O_CREAT
    - O_TRUNC
    - O_LARGEFILE
    - O_RDONLY
    path: /data/⋯
  - flags:
    - O_RDONLY
    - O_LARGEFILE
    path: /proc/⋯/smaps
  rulePolicies: null
  seccompProfile:
    spec:
      defaultAction: ""
  syscalls:
  - accept4
  - arch_prctl
  - bind
  - brk
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - dup2
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit_group
  - faccessat2
  - fcntl
  - fork
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getegid
  - geteuid
  - getgid
  - getpid
  - getppid
  - getrandom
  - getresgid
  - getresuid
  - gettid
  - getuid
  - ioctl
  - listen
  - lseek
  - lstat
  - madvise
  - membarrier
  - mmap
  - mprotect
  - munmap
  - nanosleep
  - newfstatat
  - open
  - openat
  - openat2
  - pipe
  - pipe2
  - prctl
  - prlimit64
  - read
  - readlink
  - readv
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - set_tid_address
  - setgid
  - setgroups
  - setitimer
  - setresgid
  - setresuid
  - setsockopt
  - setuid
  - socket
  - stat
  - statx
  - sysinfo
  - tgkill
  - tkill
  - umask
  - wait4
  - write
  - writev
status: {}
