apiVersion: v1
items:
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: f38dde1f29f41cb85387726073e9b2b8078661ffd9edf2049855259a2041d15b
    creationTimestamp: "2026-08-30T09:32:54Z"
    labels:
      kubescape.io/container-name: inventory
      kubescape.io/node: node-01
      kubescape.io/pod: inventory-74cbc84bfb-thnsd
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 3a4ebb74-23dd-4f82-b514-815a94ebccc4
    name: rogue-ce55c290b7acfff3
    namespace: shop
    resourceVersion: "1"
    uid: 1d70e01f-b95a-4012-a0b1-66fa78d1c78b
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 9910b08e75ea2ae15c9970e126c8a6b0d49e42cfec1a934a09a23a9e2c8ff414
    creationTimestamp: "2026-08-30T09:32:54Z"
    labels:
      kubescape.io/container-name: redis
      kubescape.io/node: cplane-01
      kubescape.io/pod: redis-88f6ffbc8-tk5mb
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: d594ec99-822f-4c39-9e0e-5b89183d829d
    name: rogue-bbcc30e70b62abf5
    namespace: shop
    resourceVersion: "1"
    uid: 6e8d76f6-5d05-4e0b-bac1-e9f55efc9d1a
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 7aadcb68b9e54f4d7ba858477d2e6921f0b93a70b4f34574d5cdd4760363d99d
    creationTimestamp: "2026-08-30T09:32:56Z"
    labels:
      kubescape.io/container-name: fx
      kubescape.io/node: node-01
      kubescape.io/pod: fx-6bf8fc86d-ngm8d
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 3a228c79-fc45-4be7-8bd2-a95a18c020ce
    name: rogue-7fee6f8732d6a521
    namespace: shop
    resourceVersion: "1"
    uid: 53cc22b5-c1c5-4d91-97ab-4e6f9761de7a
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 8478c3d8bb0a9c65b2704df9653395bc7b1f35e5ab2619c0098a4bc1ea7d199c
    creationTimestamp: "2026-08-30T09:32:59Z"
    labels:
      kubescape.io/container-name: rabbitmq
      kubescape.io/node: node-01
      kubescape.io/pod: rabbitmq-6bf65cd9dd-dczx2
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 5bad4b1c-591f-423a-8a83-bf89dbfcc266
    name: rogue-3be2a42b35f7a291
    namespace: shop
    resourceVersion: "1"
    uid: 130cd54e-9a14-4a8d-970c-a1b24bba0284
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 258105fac7c9c72becea4538a977d37cde2261bdecc7160b76480022884eadb5
    creationTimestamp: "2026-08-30T09:33:02Z"
    labels:
      kubescape.io/container-name: postgres
      kubescape.io/node: cplane-01
      kubescape.io/pod: postgres-7794ff5c69-79xzk
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: fbbc0b27-4d2f-4ebc-ba8e-28b504a4bdee
    name: rogue-6fcb5ed48d4b6439
    namespace: shop
    resourceVersion: "1"
    uid: a19775b4-50f7-4b80-b0bf-c81aede4b783
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 694b24e373bea6cb40e36ce5ca6fc96ee025f6fdf4404f385d9983887fbeb74f
    creationTimestamp: "2026-08-30T09:37:08Z"
    labels:
      kubescape.io/container-name: opsboard
      kubescape.io/node: node-01
      kubescape.io/pod: opsboard-6444c785b4-h9wrl
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: bb878504-a031-4aa1-9c1f-03b4d900d757
    name: rogue-64103b3f60c8cd99
    namespace: shop
    resourceVersion: "1"
    uid: c68e4797-efb5-4e98-b788-e5b21014bca0
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 56608df2898bc7f1a63588628e871bb047b61eb7bd1bf92195aefa7e8f642107
    creationTimestamp: "2026-08-30T09:38:08Z"
    labels:
      kubescape.io/container-name: opsboard
      kubescape.io/node: node-01
      kubescape.io/pod: opsboard-6444c785b4-h9wrl
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: bb878504-a031-4aa1-9c1f-03b4d900d757
    name: rogue-4865dd5816f69193
    namespace: shop
    resourceVersion: "1"
    uid: e155c8b3-aae0-4b93-aabd-27121c6c6f48
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 0eaa3be6dba9d77193a1bd378beb3f813fe155ed80698dab7fd0f0a23f39a436
    creationTimestamp: "2026-08-30T09:38:08Z"
    labels:
      kubescape.io/container-name: fx
      kubescape.io/node: node-01
      kubescape.io/pod: fx-6bf8fc86d-ngm8d
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 3a228c79-fc45-4be7-8bd2-a95a18c020ce
    name: rogue-ba587721949d5c11
    namespace: shop
    resourceVersion: "1"
    uid: dd8ac4aa-7643-4de5-a8f1-c8aa97a5a194
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 6194e39541d4fd73d08136931941bd33f48f1b9a70ea40fe36cacdc1b0d1dfb8
    creationTimestamp: "2026-08-30T09:38:08Z"
    labels:
      kubescape.io/container-name: rabbitmq
      kubescape.io/node: node-01
      kubescape.io/pod: rabbitmq-6bf65cd9dd-dczx2
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 5bad4b1c-591f-423a-8a83-bf89dbfcc266
    name: rogue-fb3880b7e5d91e59
    namespace: shop
    resourceVersion: "1"
    uid: 4625f9a7-d412-4406-bb56-16e9d9664829
  spec: {}
  status:
    firedAt: null
    healedAt: null
- apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
  kind: RogueArtifact
  metadata:
    annotations:
      kubescape.io/sync-checksum: 2001617017a59e5c5c791423ea55fa610df61d3f18e59012d0fda65d80ad60f3
    creationTimestamp: "2026-08-30T09:38:08Z"
    labels:
      kubescape.io/container-name: inventory
      kubescape.io/node: node-01
      kubescape.io/pod: inventory-74cbc84bfb-thnsd
      kubescape.io/rogue-learning: "true"
      kubescape.io/rogue-phase: Firing
      kubescape.io/rogue-state: rogue
      kubescape.io/workload-uid: 3a4ebb74-23dd-4f82-b514-815a94ebccc4
    name: rogue-c3e27127f14c1dcf
    namespace: shop
    resourceVersion: "1"
    uid: 5802c49e-7c49-4182-97cc-1f68a4603f0e
  spec: {}
  status:
    firedAt: null
    healedAt: null
kind: List
metadata:
  resourceVersion: ""
